<?php

namespace Ign\Bundle\GincoBundle\Repository\RawData;
use Ign\Bundle\GincoBundle\Entity\SpatialRefSys;

/**
 * SpatialRefSysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpatialRefSysRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Find all versions of DEE for a given Jdd
	 *
	 * @param Jdd $jdd
	 * @return array
	 */
	public function findByJdd(Jdd $jdd)
	{
		$qb = $this->createQueryBuilder('d')
			->join('d.jdd', 'j')
			->where('j.id = :jddId')
			->setParameter('jddId', $jdd->getId())
			->orderBy('d.version', 'DESC');

		$query = $qb->getQuery();

		return $query->getResult();
	}
}
