<?php
namespace Ign\Bundle\GincoBundle\Repository\Website;

/**
 * ApplicationParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationParameterRepository extends \Doctrine\ORM\EntityRepository {

	/**
	 * On redéfini le findAll pour renvoyer un tableau indexé par le nom.
	 */
	public function findAll() {
		return $this->getEntityManager()
			->createQuery('SELECT a FROM Ign\Bundle\GincoBundle\Entity\Website\ApplicationParameter a INDEX BY a.name ORDER BY a.name ASC')
			->getResult();
	}
}
