SET client_encoding = 'UTF8';

SET search_path = metadata_work, pg_catalog;

INSERT INTO dataset VALUES ('dataset_100', 'occ_taxon_dsr_exemple_import_shapefile', '0', NULL, 'IMPORT');

INSERT INTO format VALUES ('file_shapefile', 'FILE');

INSERT INTO file_format VALUES ('file_shapefile', 'CSV', 'fichier_shapefile', 1, 'fichier_shapefile', NULL);

INSERT INTO dataset_files VALUES ('dataset_100', 'file_shapefile');

INSERT INTO field VALUES ('altitudemax', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('altitudemin', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('altitudemoyenne', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('anneerefcommune', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('anneerefdepartement', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('cdnom', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('cdref', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('codecommune', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('codedepartement', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('codeen', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('codehabitat', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('codehabref', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('codeidcnpdispositif', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('codemaille', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('codeme', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('commentaire', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('datedetermination', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('dateme', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('deefloutage', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('denombrementmax', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('denombrementmin', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('determinateuridentite', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('determinateurmail', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('determinateurnomorganisme', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('diffusionniveauprecision', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('dspublique', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('geometrie', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('heuredatedebut', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('heuredatefin', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('identifiantorigine', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('identifiantpermanent', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('identifiantregroupementpermanent', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('jddcode', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('jddid', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('jddsourceid', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('jourdatedebut', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('jourdatefin', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('methoderegroupement', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('natureobjetgeo', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('nomcite', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('nomcommune', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('nomrefmaille', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('objetdenombrement', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('obscontexte', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('obsdescription', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('observateuridentite', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('observateurmail', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('observateurnomorganisme', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('obsmethode', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('occetatbiologique', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('occmethodedetermination', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('occnaturalite', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('occsexe', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('occstadedevie', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('occstatutbiogeographique', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('occstatutbiologique', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('organismegestionnairedonnee', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('organismestandard', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('orgtransformation', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('precisiongeometrie', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('preuveexistante', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('preuvenonnumerique', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('preuvenumerique', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('profondeurmax', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('profondeurmin', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('profondeurmoyenne', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('referencebiblio', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('refhabitat', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('statutobservation', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('statutsource', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('typedenombrement', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('typeen', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('typeinfogeocommune', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('typeinfogeodepartement', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('typeinfogeoen', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('typeinfogeomaille', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('typeinfogeome', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('typeregroupement', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('validateuridentite', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('validateurmail', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('validateurnomorganisme', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('versionen', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('versionme', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('versionrefhabitat', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('versionrefmaille', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('versiontaxref', 'file_shapefile', 'FILE');
INSERT INTO field VALUES ('jddmetadonneedeeid', 'file_shapefile', 'FILE');

INSERT INTO file_field VALUES ('altitudemax', 'file_shapefile', '0', NULL, 'altMax');
INSERT INTO file_field VALUES ('altitudemin', 'file_shapefile', '0', NULL, 'altMin');
INSERT INTO file_field VALUES ('altitudemoyenne', 'file_shapefile', '0', NULL, 'altMoy');
INSERT INTO file_field VALUES ('anneerefcommune', 'file_shapefile', '0', NULL, 'anRefCom');
INSERT INTO file_field VALUES ('anneerefdepartement', 'file_shapefile', '0', NULL, 'anRefDept');
INSERT INTO file_field VALUES ('cdnom', 'file_shapefile', '0', NULL, 'cdNom');
INSERT INTO file_field VALUES ('cdref', 'file_shapefile', '0', NULL, 'cdRef');
INSERT INTO file_field VALUES ('codeen', 'file_shapefile', '0', NULL, 'cdEN');
INSERT INTO file_field VALUES ('codehabref', 'file_shapefile', '0', NULL, 'cdHabRef');
INSERT INTO file_field VALUES ('codehabitat', 'file_shapefile', '0', NULL, 'cdHab');
INSERT INTO file_field VALUES ('codeidcnpdispositif', 'file_shapefile', '0', NULL, 'cdIDCNP');
INSERT INTO file_field VALUES ('codeme', 'file_shapefile', '0', NULL, 'cdME');
INSERT INTO file_field VALUES ('commentaire', 'file_shapefile', '0', NULL, 'comment');
INSERT INTO file_field VALUES ('denombrementmax', 'file_shapefile', '0', NULL, 'denbrMax');
INSERT INTO file_field VALUES ('determinateuridentite', 'file_shapefile', '0', NULL, 'detId');
INSERT INTO file_field VALUES ('determinateurnomorganisme', 'file_shapefile', '0', NULL, 'detNomOrg');
INSERT INTO file_field VALUES ('determinateurmail', 'file_shapefile', '0', NULL, 'detMail');
INSERT INTO file_field VALUES ('jddcode', 'file_shapefile', '0', NULL, 'jddCode');
INSERT INTO file_field VALUES ('jddid', 'file_shapefile', '0', NULL, 'jddId');
INSERT INTO file_field VALUES ('methoderegroupement', 'file_shapefile', '0', NULL, 'methGrp');
INSERT INTO file_field VALUES ('natureobjetgeo', 'file_shapefile', '0', NULL, 'natObjGeo');
INSERT INTO file_field VALUES ('nomcommune', 'file_shapefile', '0', NULL, 'nomCom');
INSERT INTO file_field VALUES ('objetdenombrement', 'file_shapefile', '0', NULL, 'objDenbr');
INSERT INTO file_field VALUES ('observateurmail', 'file_shapefile', '0', NULL, 'obsMail');
INSERT INTO file_field VALUES ('obsmethode', 'file_shapefile', '0', NULL, 'obsMeth');
INSERT INTO file_field VALUES ('observateurnomorganisme', 'file_shapefile', '0', NULL, 'obsNomOrg');
INSERT INTO file_field VALUES ('preuveexistante', 'file_shapefile', '0', NULL, 'preuveOui');
INSERT INTO file_field VALUES ('preuvenumerique', 'file_shapefile', '0', NULL, 'preuvNum');
INSERT INTO file_field VALUES ('preuvenonnumerique', 'file_shapefile', '0', NULL, 'preuvNoNum');
INSERT INTO file_field VALUES ('profondeurmax', 'file_shapefile', '0', NULL, 'profMax');
INSERT INTO file_field VALUES ('profondeurmoyenne', 'file_shapefile', '0', NULL, 'profMoy');
INSERT INTO file_field VALUES ('profondeurmin', 'file_shapefile', '0', NULL, 'profMin');
INSERT INTO file_field VALUES ('referencebiblio', 'file_shapefile', '0', NULL, 'refBiblio');
INSERT INTO file_field VALUES ('refhabitat', 'file_shapefile', '0', NULL, 'refHab');
INSERT INTO file_field VALUES ('typeen', 'file_shapefile', '0', NULL, 'typEN');
INSERT INTO file_field VALUES ('typeinfogeoen', 'file_shapefile', '0', NULL, 'typGeoEN');
INSERT INTO file_field VALUES ('typeinfogeome', 'file_shapefile', '0', NULL, 'typGeoME');
INSERT INTO file_field VALUES ('validateuridentite', 'file_shapefile', '0', NULL, 'valId');
INSERT INTO file_field VALUES ('typeregroupement', 'file_shapefile', '0', NULL, 'typGrp');
INSERT INTO file_field VALUES ('validateurmail', 'file_shapefile', '0', NULL, 'valMail');
INSERT INTO file_field VALUES ('versionme', 'file_shapefile', '0', NULL, 'vME');
INSERT INTO file_field VALUES ('validateurnomorganisme', 'file_shapefile', '0', NULL, 'valNomOrg');
INSERT INTO file_field VALUES ('versionrefhabitat', 'file_shapefile', '0', NULL, 'vRefHab');
INSERT INTO file_field VALUES ('versiontaxref', 'file_shapefile', '0', NULL, 'vTAXREF');
INSERT INTO file_field VALUES ('codedepartement', 'file_shapefile', '0', NULL, 'cdDept');
INSERT INTO file_field VALUES ('denombrementmin', 'file_shapefile', '0', NULL, 'denbrMin');
INSERT INTO file_field VALUES ('dspublique', 'file_shapefile', '1', NULL, 'dSPublique');
INSERT INTO file_field VALUES ('observateuridentite', 'file_shapefile', '0', NULL, 'obsId');
INSERT INTO file_field VALUES ('geometrie', 'file_shapefile', '0', NULL, 'WKT');
INSERT INTO file_field VALUES ('diffusionniveauprecision', 'file_shapefile', '0', NULL, 'difNivPrec');
INSERT INTO file_field VALUES ('identifiantpermanent', 'file_shapefile', '1', NULL, 'permId');
INSERT INTO file_field VALUES ('heuredatefin', 'file_shapefile', '1', 'HH:mm', 'heureFin');
INSERT INTO file_field VALUES ('heuredatedebut', 'file_shapefile', '1', 'HH:mm', 'heureDebut');
INSERT INTO file_field VALUES ('deefloutage', 'file_shapefile', '0', NULL, 'deeFlou');
INSERT INTO file_field VALUES ('identifiantorigine', 'file_shapefile', '0', NULL, 'idOrigine');
INSERT INTO file_field VALUES ('jddsourceid', 'file_shapefile', '0', NULL, 'jddSourId');
INSERT INTO file_field VALUES ('occetatbiologique', 'file_shapefile', '0', NULL, 'ocEtatBio');
INSERT INTO file_field VALUES ('occnaturalite', 'file_shapefile', '0', NULL, 'ocNat');
INSERT INTO file_field VALUES ('occsexe', 'file_shapefile', '0', NULL, 'ocSex');
INSERT INTO file_field VALUES ('occstadedevie', 'file_shapefile', '0', NULL, 'ocStade');
INSERT INTO file_field VALUES ('occstatutbiogeographique', 'file_shapefile', '0', NULL, 'ocBiogeo');
INSERT INTO file_field VALUES ('occstatutbiologique', 'file_shapefile', '0', NULL, 'ocStatBio');
INSERT INTO file_field VALUES ('obsdescription', 'file_shapefile', '0', NULL, 'obsDescr');
INSERT INTO file_field VALUES ('occmethodedetermination', 'file_shapefile', '0', NULL, 'ocMethDet');
INSERT INTO file_field VALUES ('obscontexte', 'file_shapefile', '0', NULL, 'obsCtx');
INSERT INTO file_field VALUES ('identifiantregroupementpermanent', 'file_shapefile', '0', NULL, 'permIdGrp');
INSERT INTO file_field VALUES ('typedenombrement', 'file_shapefile', '0', NULL, 'typDenbr');
INSERT INTO file_field VALUES ('organismestandard', 'file_shapefile', '0', NULL, 'orgStd');
INSERT INTO file_field VALUES ('orgtransformation', 'file_shapefile', '0', NULL, 'orgTransfo');
INSERT INTO file_field VALUES ('precisiongeometrie', 'file_shapefile', '0', NULL, 'precisGeo');
INSERT INTO file_field VALUES ('codecommune', 'file_shapefile', '0', NULL, 'cdCom');
INSERT INTO file_field VALUES ('typeinfogeocommune', 'file_shapefile', '0', NULL, 'typInfGeoC');
INSERT INTO file_field VALUES ('typeinfogeodepartement', 'file_shapefile', '0', NULL, 'typInfGeoD');
INSERT INTO file_field VALUES ('codemaille', 'file_shapefile', '0', NULL, 'cdM10');
INSERT INTO file_field VALUES ('versionrefmaille', 'file_shapefile', '0', NULL, 'vRefM10');
INSERT INTO file_field VALUES ('nomrefmaille', 'file_shapefile', '0', NULL, 'nomRefM10');
INSERT INTO file_field VALUES ('typeinfogeomaille', 'file_shapefile', '0', NULL, 'typInfGeoM');
INSERT INTO file_field VALUES ('jddmetadonneedeeid', 'file_shapefile', '0', NULL, 'jddDEEId');
INSERT INTO file_field VALUES ('jourdatedebut', 'file_shapefile', '1', 'dd/MM/yyyy', 'dateDebut');
INSERT INTO file_field VALUES ('datedetermination', 'file_shapefile', '0', 'dd/MM/yyyy', 'dateDet');
INSERT INTO file_field VALUES ('jourdatefin', 'file_shapefile', '1', 'dd/MM/yyyy', 'dateFin');
INSERT INTO file_field VALUES ('dateme', 'file_shapefile', '0', 'dd/MM/yyyy', 'dateME');
INSERT INTO file_field VALUES ('versionen', 'file_shapefile', '0', 'dd/MM/yyyy', 'veEN');
INSERT INTO file_field VALUES ('nomcite', 'file_shapefile', '1', NULL, 'nomCite');
INSERT INTO file_field VALUES ('statutobservation', 'file_shapefile', '1', NULL, 'statObs');
INSERT INTO file_field VALUES ('statutsource', 'file_shapefile', '1', NULL, 'statSource');
INSERT INTO file_field VALUES ('organismegestionnairedonnee', 'file_shapefile', '1', NULL, 'orgGestDat');

