<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */

/**
 * Display warning if user browser is not supported
 *
 * @package layouts
 */
?>

<div id="browser-not-supported">
	<div>
		<h2>Attention, vous utilisez un navigateur non recommandé</h2>
		<br>
		<p>Il se peut que votre navigateur ne soit pas entièrement compatible
			avec ce site. Pour votre sécurité et votre confort, nous vous
			recommandons d'utiliser un navigateur plus récent et à jour.</p>
		<div class="link-download">
			<button onclick="masque_div()">Continuer avec ce navigateur</button>
			<a href="http://www.mozilla.org/fr/firefox/new/" target="_blank"
				class="dl-mozilla">Télécharger <br> Mozilla Firefox
			</a> <a href="http://www.google.fr/intl/fr/chrome/browser/"
				target="_blank" class="dl-chrome">Télécharger <br> Google Chrome
			</a>
		</div>
	</div>
</div>

<script type="text/javascript">
	var browserVersion = 0;
	var supported = false;
	if (/(chrome\/[0-9]{2,3})/i.test(navigator.userAgent)) {
		browserVersion  = parseInt(navigator.userAgent.match(/(chrome\/[0-9]{2,3})/i)[0].split("/")[1]);
	    if (browserVersion > 53) {
	    	supported = true;
		}
	} else if (/(firefox\/[0-9]{2,3})/i.test(navigator.userAgent)) {
		browserVersion  = parseInt(navigator.userAgent.match(/(firefox\/[0-9]{2,3})/i)[0].split("/")[1]);
	    if (browserVersion >= 45) {
	    	supported = true;
		}
	} else if (/(MSIE\ [0-9]{1,2})/i.test(navigator.userAgent)) {
		browserVersion  = parseInt(navigator.userAgent.match(/(MSIE\ [0-9]{1,2})/i)[0].split(" ")[1]);
	    if (browserVersion >= 11) {
	    	supported = true;
		}
	} else if (/(Trident\/[7]{1,2})/i.test(navigator.userAgent)) {
	    supported = true;
	}

	if (!supported) {
		 document.getElementById('browser-not-supported').style.display = 'block';
	}else {
		 document.getElementById('browser-not-supported').style.display = 'none';
	}

	function masque_div () {
		var el = document.getElementById("browser-not-supported");
		el.parentNode.removeChild(el);
	}
</script>
