<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */

/**
 * Default layout
 *
 * @package layouts
 */
?>
<a class="footer-link" href="#openModalCopyrigth"><?php echo $this->translate('Geoportail Copyrights');?>
</a>

<div id="openModalCopyrigth" class="modalDialog">
	<div>
		<a href="#close" title="Close" class="close">X</a>
		<h1>Copyrights Géoportail</h1>
		</br>
		<h3>Pour la couche d'orthophoto :</h3>

		<table>
			<tr>
				<th class="copyrightTh">Sigle du contributeur</th>
				<th class="copyrightTh">Contributeur</th>
				<th class="copyrightTh">LOGO</th>
				<th class="copyrightTh">URL du site</th>
			</tr>
			<tr>
				<td>IGN</td>
				<td>Institut national de l'information géographique et forestière</td>
				<td><img src="http://wxs.ign.fr/static/logos/IGN/IGN.gif" alt="logo" /></td>
				<td>http://www.ign.fr</td>
			</tr>
			<tr>
				<td>CRCORSE</td>
				<td>CRCORSE</td>
				<td><img src="http://wxs.ign.fr/static/logos/CRCORSE/CRCORSE.gif"
					alt="logo" /></td>
				<td>http://www.corse.fr//</td>
			</tr>
			<tr>
				<td>e-Megalis</td>
				<td>Syndicat mixte de coopération territoriale (e-Megalis)</td>
				<td><img
					src="http://wxs.ign.fr/static/logos/e-Megalis/e-Megalis.gif"
					alt="logo" /></td>
				<td>http://www.e-megalisbretagne.org//</td>


			<tr>
			</tr>
			<td>FEDER2</td>
			<td>Fonds européen de développement économique et régional</td>
			<td><img src="http://wxs.ign.fr/static/logos/FEDER2/FEDER2.gif"
				alt="logo" /></td>
			<td>http://www.europe-en-france.gouv.fr/</td>
			</tr>
			<tr>
				<td>CRAIG</td>
				<td>Centre Régional Auvergnat de l'Information Géographique (CRAIG)</td>
				<td><img src="http://wxs.ign.fr/static/logos/CRAIG/CRAIG.gif"
					alt="logo" /></td>
				<td>http://www.craig.fr</td>
			</tr>
			<tr>
				<td>CNES_AUVERGNE</td>
				<td>Centre national d'études spatiales (CNES)</td>
				<td><img
					src="http://wxs.ign.fr/static/logos/CNES_AUVERGNE/CNES_AUVERGNE.gif"
					alt="logo" /></td>
				<td>http://www.cnes.fr/</td>
			</tr>
			<tr>
				<td>PPIGE</td>
				<td>PPIGE</td>
				<td><img src="http://wxs.ign.fr/static/logos/PPIGE/PPIGE.gif"
					alt="logo" /></td>
				<td>http://www.ppige-npdc.fr/</td>
			</tr>
			<tr>
				<td>SIGLR</td>
				<td>SIGLR</td>
				<td><img src="http://wxs.ign.fr/static/logos/SIGLR/SIGLR.gif"
					alt="logo" /></td>
				<td>http://www.siglr.org//</td>
			</tr>
			<tr>
				<td>CG06</td>
				<td>Département Alpes Maritimes (06) en partenariat avec :
					Groupement Orthophoto 06 (NCA, Ville de Cannes, CARF, CASA,CG06, CA
					de Grasse)</td>
				<td><img src="http://wxs.ign.fr/static/logos/CG06/CG06.gif"
					alt="logo" /></td>
				<td>http://www.cg06.fr</td>
			</tr>
			<tr>
				<td>RGD_SAVOIE</td>
				<td>Régie de Gestion de Données des Pays de Savoie (RGD 73-74)</td>
				<td><img
					src="http://wxs.ign.fr/static/logos/RGD_SAVOIE/RGD_SAVOIE.gif"
					alt="logo" /></td>
				<td>http://www.rgd.fr</td>
			</tr>
			<tr>
				<td>CG45</td>
				<td>Le conseil général du Loiret</td>
				<td><img src="http://wxs.ign.fr/static/logos/CG45/CG45.gif"
					alt="logo" /></td>
				<td>http://www.loiret.com</td>
			</tr>
			<tr>
				<td>CNES_971</td>
				<td>Centre national d'études spatiales (CNES)</td>
				<td><img src="http://wxs.ign.fr/static/logos/CNES_971/CNES_971.gif"
					alt="logo" /></td>
				<td>http://www.cnes.fr/</td>
			</tr>
			<tr>
				<td>CNES_972</td>
				<td>Centre national d'études spatiales (CNES)</td>
				<td><img src="http://wxs.ign.fr/static/logos/CNES_972/CNES_972.gif"
					alt="logo" /></td>
				<td>http://www.cnes.fr/</td>
			</tr>
			<tr>
				<td>DITTT</td>
				<td>Direction des Infrastructures, de la Topographie et des
					Transports Terrestres</td>
				<td><img src="http://wxs.ign.fr/static/logos/DITTT/DITTT.gif"
					alt="logo" /></td>
				<td>http://www.dittt.gouv.nc/portal/page/portal/dittt/</td>
			</tr>
			<tr>
				<td>CNES_978</td>
				<td>Centre national d'études spatiales (CNES)</td>
				<td><img src="http://wxs.ign.fr/static/logos/CNES_978/CNES_978.gif"
					alt="logo" /></td>
				<td>http://www.cnes.fr/</td>
			</tr>
			<tr>
				<td>CNES_ALSACE</td>
				<td>Centre national d'études spatiales (CNES)</td>
				<td><img
					src="http://wxs.ign.fr/static/logos/CNES_ALSACE/CNES_ALSACE.gif"
					alt="logo" /></td>
				<td>http://www.cnes.fr/</td>
			</tr>
			<tr>
				<td>CNES</td>
				<td>Centre national d'études spatiales (CNES)</td>
				<td><img src="http://wxs.ign.fr/static/logos/CNES/CNES.gif"
					alt="logo" /></td>
				<td>http://www.cnes.fr/</td>
			</tr>
			<tr>
				<td>ASTRIUM</td>
				<td>Airbus Defence and Space</td>
				<td><img src="http://wxs.ign.fr/static/logos/ASTRIUM/ASTRIUM.gif"
					alt="logo" /></td>
				<td>http://www.geo-airbusds.com/</td>
			</tr>
			<tr>
				<td>CNES_974</td>
				<td>Centre national d'études spatiales (CNES)</td>
				<td><img src="http://wxs.ign.fr/static/logos/CNES_974/CNES_974.gif"
					alt="logo" /></td>
				<td>http://www.cnes.fr/</td>
			</tr>
			<tr>
				<td>CNES_975</td>
				<td>Centre national d'études spatiales (CNES)</td>
				<td><img src="http://wxs.ign.fr/static/logos/CNES_975/CNES_975.gif"
					alt="logo" /></td>
				<td>http://www.cnes.fr/</td>
			</tr>
			<tr>
				<td>CNES_976</td>
				<td>Centre national d'études spatiales (CNES)</td>
				<td><img src="http://wxs.ign.fr/static/logos/CNES_976/CNES_976.gif"
					alt="logo" /></td>
				<td>http://www.cnes.fr/</td>
			</tr>
			<tr>
				<td>CNES_977</td>
				<td>Centre national d'études spatiales (CNES)</td>
				<td><img src="http://wxs.ign.fr/static/logos/CNES_977/CNES_977.gif"
					alt="logo" /></td>
				<td>http://www.cnes.fr/</td>
			</tr>
			<tr>
				<td>PLANETOBSERVER</td>
				<td>PlanetObserver (images satellites)</td>
				<td><img
					src="http://wxs.ign.fr/static/logos/PLANETOBSERVER/PLANETOBSERVER.gif"
					alt="logo" /></td>
				<td>http://www.planetobserver.com/</td>
			</tr>
			<tr>
				<td>MPM</td>
				<td>Marseille Provence Métropole</td>
				<td><img src="http://wxs.ign.fr/static/logos/MPM/MPM.gif" alt="logo" /></td>
				<td>http://www.marseille-provence.com/</td>
			</tr>
		</table>

		<h3>Pour la couche de plans IGN :</h3>

		<table>
			<tr>
				<th class="copyrightTh">Sigle du contributeur</th>
				<th class="copyrightTh">Contributeur</th>
				<th class="copyrightTh">LOGO</th>
				<th class="copyrightTh">URL du site</th>
			</tr>
			<tr>
				<td>IGN</td>
				<td>Institut national de l'information géographique et forestière</td>
				<td><img src="http://wxs.ign.fr/static/logos/IGN/IGN.gif" alt="logo"></td>
				<td>http://www.ign.fr</td>
			</tr>
			<tr>
				<td>EUROGEOGRAPHICS</td>
				<td>Eurogeographics</td>
				<td><img
					src="http://wxs.ign.fr/static/logos/EUROGEOGRAPHICS/EUROGEOGRAPHICS.gif"
					alt="logo"></td>
				<td>http://www.eurogeographics.org/</td>
			</tr>
		</table>

	</div>
</div>