<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */

/**
 * Legal notices
 *
 * @package layouts
 */
?>
<a class="footer-link" href="#openModalLegalNotices"><?php echo $this->translate('Legal notices');?> </a>

<div id="openModalLegalNotices" class="modalDialog">
	<div>
		<a href="#close" title="Close" class="close">X</a>
		<h1>Mentions légales</h1>
		</br>
		<h2>Informations Éditeurs</h2>
		<h3>Service gestionnaire du site</h3>

		<p>Ministère de l’Énergie, de l'Environnement et de la Mer</p>
		<p>Direction de l'eau et de la biodiversité</p>
		<p>Arche Sud - 92055 La Défense Cedex</p>
		<p>Téléphone : 01 40 81 19 61</p>
		<p>Directeur de la publication : François MITTEAULT, directeur de
			l'eau et de la biodiversité</p>
		<p>Coordination : Yannick Lebeau, chef de projet "Système
			d'information sur la Nature et les Paysages"</p>
		<strong><p>Contact (IGN)</p>
			<p>à compléter</p></strong>

		<h3>Hébergement du site :</h3>
		<strong>à compléter</strong>


		<h3>Conception et développement :</h3>

		<strong><p>IGN</p>
			<p>à compléter</p>
			<p>MNHN</p>
			<p>à compléter</p></strong>
		<h4>Propriété intellectuelle du code</h4>

		Les développements (conception du site, écrans, procédures,
		fonctionnalités,etc..) sont la co-propriété du MEER, de l'IGN et du
		MNHN. Ils disposent conjointement pour le monde entier des droits
		patrimoniaux sur ces développements, qui comprennent notamment les
		droits de reproduction, de représentation d’adaptation, de traduction,
		aux fins de diffusion à des tiers sous licences d’utilisation ou
		d’exploitation. <strong>Le site utilise des composants Open Source, le
			code du composant OGAM est sous licence EUPL, accessible sur la forge
			:</strong>

		<h4>Données</h4>

		Les données de biodiversité contenues sur le site font l'objet d'une
		licence distincte accessible à l'adresse :
		www.naturefrance.fr/actions/ginco

		<h4>Données personnelles</h4>

		<p>Lorsque des données présentes sur ce site ont un caractère
			nominatif, les utilisateurs doivent en faire un usage conforme aux
			réglementations en vigueur et aux recommandations de la Commission
			nationale de l'informatique et des libertés (CNIL). Conformément à la
			loi Informatique et Liberté 78-17 du 6 janvier 1978 modifiée, vous
			disposez d'un droit d'opposition (art. 38), d'accès (art. 39), de
			rectification ou de suppression (art. 40) des données qui vous
			concernent. Vous pouvez exercer ce droit en vous adressant au
			ministère du Développement durable. Ce droit s'exerce, en justifiant
			de son identité :</p>
		<ul>
			<li>par voie postale : Ministère du Développement durable, Direction
				de l'eau et de la biodiversité - Arche Sud 92055 La Défense Cedex</li>
			<li>par courrier électronique</li>
		</ul>
		<p>Toutes les données personnelles qui sont recueillies sont traitées
			avec la plus stricte confidentialité. En particulier, le ministère du
			Développement durable s’engage à respecter la confidentialité des
			messages e-mails transmis au moyen d’une messagerie électronique.</p>

		<h3>Responsabilité du ministère</h3>

		<p>Les informations proposées sur ce site le sont au titre de service
			rendu aux adhérents du système d'information sur la nature et les
			paysages Malgré tout le soin apporté à l’actualisation des textes
			officiels et à la vérification des contenus, les documents mis en
			ligne ne sauraient engager la responsabilité du ministère. Les
			informations et/ou documents disponibles sur ce site sont
			susceptibles d’être modifiés à tout moment, et peuvent faire l’objet
			de mises à jour. Le ministère ne pourra en aucun cas être tenu
			responsable de tout dommage de quelque nature qu’il soit résultant de
			l’interprétation ou de l’utilisation des informations et/ou documents
			disponibles sur ce site.</p>

		<h2>Accessibilité du site</h2>

		<h3>Disponibilité du site</h3>

		<p>L’éditeur s’efforce de permettre l’accès au site 24 heures sur 24,
			7 jours sur 7, sauf en cas de force majeure ou d’un événement hors du
			contrôle du ministère du Développement durable, et sous réserve des
			éventuelles pannes et interventions de maintenance nécessaires au bon
			fonctionnement du site et des services. Par conséquent, le ministère
			du Développement durable ne peut garantir une disponibilité du site
			et/ou des services, une fiabilité des transmissions et des
			performances en termes de temps de réponse ou de qualité. Il n’est
			prévu aucune assistance technique vis-à-vis de l’utilisateur que ce
			soit par des moyens électronique ou téléphonique. La responsabilité
			de l’éditeur ne saurait être engagée en cas d’impossibilité d’accès à
			ce site et/ou d’utilisation des services. Le ministère du
			Développement durable peut être amené à interrompre le site ou une
			partie des services, à tout moment sans préavis, le tout sans droit à
			indemnités. L’utilisateur reconnaît et accepte que le ministère du
			Développement durable ne soit pas responsable des interruptions, et
			des conséquences qui peuvent en découler pour l’utilisateur ou tout
			tiers.</p>

		<h3>Droit applicable</h3>

		<p>Quel que soit le lieu d’utilisation, le présent site est régi par
			le droit français. En cas de contestation éventuelle, et après
			l’échec de toute tentative de recherche d’une solution amiable, les
			tribunaux français seront seuls compétents pour connaître de ce
			litige. Pour toute question relative aux présentes conditions
			d’utilisation du site, vous pouvez écrire à l’adresse suivante :


		<p>Ministère de l'Energie, de l'Environnement et de la Mer (MEER)</p>
		<p>Direction de l'eau et de la biodiversité</p>
		<p>Sous-Direction de la protection et de la valorisation des espèces
			et de leurs milieux</p>
		<p>Arche Sud - 92055 La Défense Cedex</p>

		<h3>Acceptation des conditions d’utilisation</h3>

		<p>L’utilisateur reconnaît avoir pris connaissance des conditions
			d’utilisation, au moment de sa connexion vers le site et déclare
			expressément les accepter sans réserve.</p>

		<h3>Modifications des conditions générales d’utilisation</h3>

		<p>Le ministère en charge du patrimoine naturel se réserve la
			possibilité de modifier, à tout moment et sans préavis, les présentes
			conditions d’utilisation afin de les adapter aux évolutions du site
			et/ou de son exploitation.</p>
	</div>
</div>