<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */

/**
 * MNHN Copyrights
 *
 * @package layouts
 */
?>
<a class="footer-link" href="#openMNHNModalCopyrigth"><?php echo $this->translate('MNHN Copyrights');?>
</a>

<div id="openMNHNModalCopyrigth" class="modalDialog">
	<div>
		<a href="#close" title="Close" class="close">X</a>
		<h1>Copyrights MNHN</h1>
		</br>
		<h3>Listes de références de l'INPN :</h3>
			<p>Taxref, sensibilité, Habref, Espaces naturels.</p>
			<img src="/img/logo_INPN.jpg" alt="logo-ign"/>

		<h3>Application métadonnées :</h3>
		<table>
			<tr>
				<th class="copyrightTh">Organisme en charge</th>
				<th class="copyrightTh">LOGO</th>
				<th class="copyrightTh">URL du site</th>
			</tr>
			<tr>
				<td>Muséum national d'Histoire naturelle (MNHN)</td>
				<td><img src="" alt="logo"></td>
				<td>http://inpn.mnhn.fr/mtd</td>
			</tr>
		</table>

	</div>
</div>