<?php
namespace Ign\Bundle\OGAMBundle\Repository\Website;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository {

	/**
	 * Count the number of users of a role.
	 *
	 * @param String $roleCode        	
	 * @return Integer
	 */
	public function userCount($roleCode) {
		$qm = $this->getEntityManager();
		
		$rsm = new ResultSetMapping();
		$rsm->addScalarResult('count', 'count');
		
		$query = $qm->createNativeQuery('SELECT count(*) FROM website.role_to_user WHERE role_code = ?', $rsm);
		$query->setParameter(1, $roleCode);
		
		return $query->getSingleScalarResult();
	}

	/**
	 * Sets to false all default column.
	 *
	 * @return Integer
	 */
	public function removeDefaultValue() {
		$conn = $this->_em->getConnection();
		$sql = "UPDATE role SET is_default = FALSE WHERE is_default = TRUE";

		$stmt = $conn->prepare($sql);
		$stmt->execute();

		return $stmt->fetchColumn();
	}

}
