<?php
namespace Ign\Bundle\OGAMBundle\Repository\Mapping;

/**
 * ZoomLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoomLevelRepository extends \Doctrine\ORM\EntityRepository {

	/**
	 * Get the list of available zoom levels resolutions.
	 * 
	 * @return number[]
	 */
	function getResolutions() {
		$zoomLevels = $this->findBy([
			"isMapZoomLevel" => true
		]);
		$resolutions = [];
		foreach ($zoomLevels as $zoomLevel) {
			$resolutions[] = $zoomLevel->getResolution();
		}
		return $resolutions;
	}
}
