<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */


/**
 * View for the upload of one or more data file.
 * @package views
 */
?>


<h1>
   <?php echo $this->translate('Manage datasets');?> - <?php echo $this->translate('Import a new dataset');?>
</h1>

<h2>
  <?php echo $this->translate('Dataset');?> : <?php echo $this->dataset->label;?>
</h2>

<?php echo $this->form ?>
<?php echo $this->errorMessage ?>