<wfs:FeatureCollection numberReturned="1" timeStamp="2005-06-29T09:30:30Z" numberMatched="1" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sinp="http://www.naturefrance.fr/sinp/" xmlns:gml="http://www.opengis.net/gml/3.2" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.naturefrance.fr/sinp/ observation0.4.xsd">
	<wfs:member>
		<sinp:Observation gml:id="ID_300012_102901">
			<sinp:statusSource>TE</sinp:statusSource>
			<sinp:identifiantPermament></sinp:identifiantPermament>
			<sinp:statusObservation>PR</sinp:statusObservation>
			<sinp:cdNom>102901</sinp:cdNom>
			<sinp:georeference>
				<sinp:Georeference>
					<sinp:geometriePoint>
						<gml:Point gml:id="p300012_102901" srsName="urn:ogc:def:crs:EPSG:6.6:2154">
							<gml:pos>829500 6989368</gml:pos>
						</gml:Point>
					</sinp:geometriePoint>
				</sinp:Georeference>
			</sinp:georeference>
			<sinp:observateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:observateur>
			<sinp:validateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:validateur>
			<sinp:determinateur>
				<sinp:Personne>
					<sinp:identite/>
				</sinp:Personne>
			</sinp:determinateur>
			<sinp:empriseTemporelle>
				<sinp:EmpriseTemporelle>
					<sinp:dateDebut>2007-11-13T00:00:00Z</sinp:dateDebut>
					<sinp:dateFin>2007-11-13T00:00:00Z</sinp:dateFin>
				</sinp:EmpriseTemporelle>
			</sinp:empriseTemporelle>
			<sinp:source>
				<sinp:Source>
					<sinp:jddId></sinp:jddId>
					<sinp:jddCode>exploitation</sinp:jddCode>
					<sinp:dSPublique>PU</sinp:dSPublique>
					<sinp:identifiantOrigine>300012_102901</sinp:identifiantOrigine>
					<sinp:codeIDCNP></sinp:codeIDCNP>
					<sinp:sensible>Non</sinp:sensible>
					<sinp:nomScientifiqueCite></sinp:nomScientifiqueCite>
				</sinp:Source>
			</sinp:source>
		</sinp:Observation>
	</wfs:member>
	<wfs:member>
		<sinp:Observation gml:id="ID_300012_103320">
			<sinp:statusSource>TE</sinp:statusSource>
			<sinp:identifiantPermament></sinp:identifiantPermament>
			<sinp:statusObservation>PR</sinp:statusObservation>
			<sinp:cdNom>103320</sinp:cdNom>
			<sinp:georeference>
				<sinp:Georeference>
					<sinp:geometriePoint>
						<gml:Point gml:id="p300012_103320" srsName="urn:ogc:def:crs:EPSG:6.6:2154">
							<gml:pos>829500 6989368</gml:pos>
						</gml:Point>
					</sinp:geometriePoint>
				</sinp:Georeference>
			</sinp:georeference>
			<sinp:observateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:observateur>
			<sinp:validateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:validateur>
			<sinp:determinateur>
				<sinp:Personne>
					<sinp:identite/>
				</sinp:Personne>
			</sinp:determinateur>
			<sinp:empriseTemporelle>
				<sinp:EmpriseTemporelle>
					<sinp:dateDebut>2007-11-13T00:00:00Z</sinp:dateDebut>
					<sinp:dateFin>2007-11-13T00:00:00Z</sinp:dateFin>
				</sinp:EmpriseTemporelle>
			</sinp:empriseTemporelle>
			<sinp:source>
				<sinp:Source>
					<sinp:jddId></sinp:jddId>
					<sinp:jddCode>exploitation</sinp:jddCode>
					<sinp:dSPublique>PU</sinp:dSPublique>
					<sinp:identifiantOrigine>300012_103320</sinp:identifiantOrigine>
					<sinp:codeIDCNP></sinp:codeIDCNP>
					<sinp:sensible>Non</sinp:sensible>
					<sinp:nomScientifiqueCite></sinp:nomScientifiqueCite>
				</sinp:Source>
			</sinp:source>
		</sinp:Observation>
	</wfs:member>
	<wfs:member>
		<sinp:Observation gml:id="ID_300012_103514">
			<sinp:statusSource>TE</sinp:statusSource>
			<sinp:identifiantPermament></sinp:identifiantPermament>
			<sinp:statusObservation>PR</sinp:statusObservation>
			<sinp:cdNom>103514</sinp:cdNom>
			<sinp:georeference>
				<sinp:Georeference>
					<sinp:geometriePoint>
						<gml:Point gml:id="p300012_103514" srsName="urn:ogc:def:crs:EPSG:6.6:2154">
							<gml:pos>829500 6989368</gml:pos>
						</gml:Point>
					</sinp:geometriePoint>
				</sinp:Georeference>
			</sinp:georeference>
			<sinp:observateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:observateur>
			<sinp:validateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:validateur>
			<sinp:determinateur>
				<sinp:Personne>
					<sinp:identite/>
				</sinp:Personne>
			</sinp:determinateur>
			<sinp:empriseTemporelle>
				<sinp:EmpriseTemporelle>
					<sinp:dateDebut>2007-11-13T00:00:00Z</sinp:dateDebut>
					<sinp:dateFin>2007-11-13T00:00:00Z</sinp:dateFin>
				</sinp:EmpriseTemporelle>
			</sinp:empriseTemporelle>
			<sinp:source>
				<sinp:Source>
					<sinp:jddId></sinp:jddId>
					<sinp:jddCode>exploitation</sinp:jddCode>
					<sinp:dSPublique>PU</sinp:dSPublique>
					<sinp:identifiantOrigine>300012_103514</sinp:identifiantOrigine>
					<sinp:codeIDCNP></sinp:codeIDCNP>
					<sinp:sensible>Non</sinp:sensible>
					<sinp:nomScientifiqueCite></sinp:nomScientifiqueCite>
				</sinp:Source>
			</sinp:source>
		</sinp:Observation>
	</wfs:member>
	<wfs:member>
		<sinp:Observation gml:id="ID_300012_108718">
			<sinp:statusSource>TE</sinp:statusSource>
			<sinp:identifiantPermament></sinp:identifiantPermament>
			<sinp:statusObservation>PR</sinp:statusObservation>
			<sinp:cdNom>108718</sinp:cdNom>
			<sinp:georeference>
				<sinp:Georeference>
					<sinp:geometriePoint>
						<gml:Point gml:id="p300012_108718" srsName="urn:ogc:def:crs:EPSG:6.6:2154">
							<gml:pos>829500 6989368</gml:pos>
						</gml:Point>
					</sinp:geometriePoint>
				</sinp:Georeference>
			</sinp:georeference>
			<sinp:observateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:observateur>
			<sinp:validateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:validateur>
			<sinp:determinateur>
				<sinp:Personne>
					<sinp:identite/>
				</sinp:Personne>
			</sinp:determinateur>
			<sinp:empriseTemporelle>
				<sinp:EmpriseTemporelle>
					<sinp:dateDebut>2007-11-13T00:00:00Z</sinp:dateDebut>
					<sinp:dateFin>2007-11-13T00:00:00Z</sinp:dateFin>
				</sinp:EmpriseTemporelle>
			</sinp:empriseTemporelle>
			<sinp:source>
				<sinp:Source>
					<sinp:jddId></sinp:jddId>
					<sinp:jddCode>exploitation</sinp:jddCode>
					<sinp:dSPublique>PU</sinp:dSPublique>
					<sinp:identifiantOrigine>300012_108718</sinp:identifiantOrigine>
					<sinp:codeIDCNP></sinp:codeIDCNP>
					<sinp:sensible>Non</sinp:sensible>
					<sinp:nomScientifiqueCite></sinp:nomScientifiqueCite>
				</sinp:Source>
			</sinp:source>
		</sinp:Observation>
	</wfs:member>
	<wfs:member>
		<sinp:Observation gml:id="ID_300012_116265">
			<sinp:statusSource>TE</sinp:statusSource>
			<sinp:identifiantPermament></sinp:identifiantPermament>
			<sinp:statusObservation>PR</sinp:statusObservation>
			<sinp:cdNom>116265</sinp:cdNom>
			<sinp:georeference>
				<sinp:Georeference>
					<sinp:geometriePoint>
						<gml:Point gml:id="p300012_116265" srsName="urn:ogc:def:crs:EPSG:6.6:2154">
							<gml:pos>829500 6989368</gml:pos>
						</gml:Point>
					</sinp:geometriePoint>
				</sinp:Georeference>
			</sinp:georeference>
			<sinp:observateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:observateur>
			<sinp:validateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:validateur>
			<sinp:determinateur>
				<sinp:Personne>
					<sinp:identite/>
				</sinp:Personne>
			</sinp:determinateur>
			<sinp:empriseTemporelle>
				<sinp:EmpriseTemporelle>
					<sinp:dateDebut>2007-11-13T00:00:00Z</sinp:dateDebut>
					<sinp:dateFin>2007-11-13T00:00:00Z</sinp:dateFin>
				</sinp:EmpriseTemporelle>
			</sinp:empriseTemporelle>
			<sinp:source>
				<sinp:Source>
					<sinp:jddId></sinp:jddId>
					<sinp:jddCode>exploitation</sinp:jddCode>
					<sinp:dSPublique>PU</sinp:dSPublique>
					<sinp:identifiantOrigine>300012_116265</sinp:identifiantOrigine>
					<sinp:codeIDCNP></sinp:codeIDCNP>
					<sinp:sensible>Non</sinp:sensible>
					<sinp:nomScientifiqueCite></sinp:nomScientifiqueCite>
				</sinp:Source>
			</sinp:source>
		</sinp:Observation>
	</wfs:member>
	<wfs:member>
		<sinp:Observation gml:id="ID_300012_119097">
			<sinp:statusSource>TE</sinp:statusSource>
			<sinp:identifiantPermament></sinp:identifiantPermament>
			<sinp:statusObservation>PR</sinp:statusObservation>
			<sinp:cdNom>119097</sinp:cdNom>
			<sinp:georeference>
				<sinp:Georeference>
					<sinp:geometriePoint>
						<gml:Point gml:id="p300012_119097" srsName="urn:ogc:def:crs:EPSG:6.6:2154">
							<gml:pos>829500 6989368</gml:pos>
						</gml:Point>
					</sinp:geometriePoint>
				</sinp:Georeference>
			</sinp:georeference>
			<sinp:observateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:observateur>
			<sinp:validateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:validateur>
			<sinp:determinateur>
				<sinp:Personne>
					<sinp:identite/>
				</sinp:Personne>
			</sinp:determinateur>
			<sinp:empriseTemporelle>
				<sinp:EmpriseTemporelle>
					<sinp:dateDebut>2007-11-13T00:00:00Z</sinp:dateDebut>
					<sinp:dateFin>2007-11-13T00:00:00Z</sinp:dateFin>
				</sinp:EmpriseTemporelle>
			</sinp:empriseTemporelle>
			<sinp:source>
				<sinp:Source>
					<sinp:jddId></sinp:jddId>
					<sinp:jddCode>exploitation</sinp:jddCode>
					<sinp:dSPublique>PU</sinp:dSPublique>
					<sinp:identifiantOrigine>300012_119097</sinp:identifiantOrigine>
					<sinp:codeIDCNP></sinp:codeIDCNP>
					<sinp:sensible>Non</sinp:sensible>
					<sinp:nomScientifiqueCite></sinp:nomScientifiqueCite>
				</sinp:Source>
			</sinp:source>
		</sinp:Observation>
	</wfs:member>
	<wfs:member>
		<sinp:Observation gml:id="ID_300012_126035">
			<sinp:statusSource>TE</sinp:statusSource>
			<sinp:identifiantPermament></sinp:identifiantPermament>
			<sinp:statusObservation>PR</sinp:statusObservation>
			<sinp:cdNom>126035</sinp:cdNom>
			<sinp:georeference>
				<sinp:Georeference>
					<sinp:geometriePoint>
						<gml:Point gml:id="p300012_126035" srsName="urn:ogc:def:crs:EPSG:6.6:2154">
							<gml:pos>829500 6989368</gml:pos>
						</gml:Point>
					</sinp:geometriePoint>
				</sinp:Georeference>
			</sinp:georeference>
			<sinp:observateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:observateur>
			<sinp:validateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:validateur>
			<sinp:determinateur>
				<sinp:Personne>
					<sinp:identite/>
				</sinp:Personne>
			</sinp:determinateur>
			<sinp:empriseTemporelle>
				<sinp:EmpriseTemporelle>
					<sinp:dateDebut>2007-11-13T00:00:00Z</sinp:dateDebut>
					<sinp:dateFin>2007-11-13T00:00:00Z</sinp:dateFin>
				</sinp:EmpriseTemporelle>
			</sinp:empriseTemporelle>
			<sinp:source>
				<sinp:Source>
					<sinp:jddId></sinp:jddId>
					<sinp:jddCode>exploitation</sinp:jddCode>
					<sinp:dSPublique>PU</sinp:dSPublique>
					<sinp:identifiantOrigine>300012_126035</sinp:identifiantOrigine>
					<sinp:codeIDCNP></sinp:codeIDCNP>
					<sinp:sensible>Non</sinp:sensible>
					<sinp:nomScientifiqueCite></sinp:nomScientifiqueCite>
				</sinp:Source>
			</sinp:source>
		</sinp:Observation>
	</wfs:member>
	<wfs:member>
		<sinp:Observation gml:id="ID_300012_128345">
			<sinp:statusSource>TE</sinp:statusSource>
			<sinp:identifiantPermament></sinp:identifiantPermament>
			<sinp:statusObservation>PR</sinp:statusObservation>
			<sinp:cdNom>128345</sinp:cdNom>
			<sinp:georeference>
				<sinp:Georeference>
					<sinp:geometriePoint>
						<gml:Point gml:id="p300012_128345" srsName="urn:ogc:def:crs:EPSG:6.6:2154">
							<gml:pos>829500 6989368</gml:pos>
						</gml:Point>
					</sinp:geometriePoint>
				</sinp:Georeference>
			</sinp:georeference>
			<sinp:observateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:observateur>
			<sinp:validateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:validateur>
			<sinp:determinateur>
				<sinp:Personne>
					<sinp:identite/>
				</sinp:Personne>
			</sinp:determinateur>
			<sinp:empriseTemporelle>
				<sinp:EmpriseTemporelle>
					<sinp:dateDebut>2007-11-13T00:00:00Z</sinp:dateDebut>
					<sinp:dateFin>2007-11-13T00:00:00Z</sinp:dateFin>
				</sinp:EmpriseTemporelle>
			</sinp:empriseTemporelle>
			<sinp:source>
				<sinp:Source>
					<sinp:jddId></sinp:jddId>
					<sinp:jddCode>exploitation</sinp:jddCode>
					<sinp:dSPublique>PU</sinp:dSPublique>
					<sinp:identifiantOrigine>300012_128345</sinp:identifiantOrigine>
					<sinp:codeIDCNP></sinp:codeIDCNP>
					<sinp:sensible>Non</sinp:sensible>
					<sinp:nomScientifiqueCite></sinp:nomScientifiqueCite>
				</sinp:Source>
			</sinp:source>
		</sinp:Observation>
	</wfs:member>
	<wfs:member>
		<sinp:Observation gml:id="ID_300012_139584">
			<sinp:statusSource>TE</sinp:statusSource>
			<sinp:identifiantPermament></sinp:identifiantPermament>
			<sinp:statusObservation>PR</sinp:statusObservation>
			<sinp:cdNom>139584</sinp:cdNom>
			<sinp:georeference>
				<sinp:Georeference>
					<sinp:geometriePoint>
						<gml:Point gml:id="p300012_139584" srsName="urn:ogc:def:crs:EPSG:6.6:2154">
							<gml:pos>829500 6989368</gml:pos>
						</gml:Point>
					</sinp:geometriePoint>
				</sinp:Georeference>
			</sinp:georeference>
			<sinp:observateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:observateur>
			<sinp:validateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:validateur>
			<sinp:determinateur>
				<sinp:Personne>
					<sinp:identite/>
				</sinp:Personne>
			</sinp:determinateur>
			<sinp:empriseTemporelle>
				<sinp:EmpriseTemporelle>
					<sinp:dateDebut>2007-11-13T00:00:00Z</sinp:dateDebut>
					<sinp:dateFin>2007-11-13T00:00:00Z</sinp:dateFin>
				</sinp:EmpriseTemporelle>
			</sinp:empriseTemporelle>
			<sinp:source>
				<sinp:Source>
					<sinp:jddId></sinp:jddId>
					<sinp:jddCode>exploitation</sinp:jddCode>
					<sinp:dSPublique>PU</sinp:dSPublique>
					<sinp:identifiantOrigine>300012_139584</sinp:identifiantOrigine>
					<sinp:codeIDCNP></sinp:codeIDCNP>
					<sinp:sensible>Non</sinp:sensible>
					<sinp:nomScientifiqueCite></sinp:nomScientifiqueCite>
				</sinp:Source>
			</sinp:source>
		</sinp:Observation>
	</wfs:member>
	<wfs:member>
		<sinp:Observation gml:id="ID_300012_433976">
			<sinp:statusSource>TE</sinp:statusSource>
			<sinp:identifiantPermament></sinp:identifiantPermament>
			<sinp:statusObservation>PR</sinp:statusObservation>
			<sinp:cdNom>433976</sinp:cdNom>
			<sinp:georeference>
				<sinp:Georeference>
					<sinp:geometriePoint>
						<gml:Point gml:id="p300012_433976" srsName="urn:ogc:def:crs:EPSG:6.6:2154">
							<gml:pos>829500 6989368</gml:pos>
						</gml:Point>
					</sinp:geometriePoint>
				</sinp:Georeference>
			</sinp:georeference>
			<sinp:observateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:observateur>
			<sinp:validateur>
				<sinp:Personne>
					<sinp:identite>Anonyme</sinp:identite>
					<sinp:organisme>
						<sinp:Organisme>
							<sinp:nom>IGN</sinp:nom>
						</sinp:Organisme>
					</sinp:organisme>
				</sinp:Personne>
			</sinp:validateur>
			<sinp:determinateur>
				<sinp:Personne>
					<sinp:identite/>
				</sinp:Personne>
			</sinp:determinateur>
			<sinp:empriseTemporelle>
				<sinp:EmpriseTemporelle>
					<sinp:dateDebut>2007-11-13T00:00:00Z</sinp:dateDebut>
					<sinp:dateFin>2007-11-13T00:00:00Z</sinp:dateFin>
				</sinp:EmpriseTemporelle>
			</sinp:empriseTemporelle>
			<sinp:source>
				<sinp:Source>
					<sinp:jddId></sinp:jddId>
					<sinp:jddCode>exploitation</sinp:jddCode>
					<sinp:dSPublique>PU</sinp:dSPublique>
					<sinp:identifiantOrigine>300012_433976</sinp:identifiantOrigine>
					<sinp:codeIDCNP></sinp:codeIDCNP>
					<sinp:sensible>Non</sinp:sensible>
					<sinp:nomScientifiqueCite></sinp:nomScientifiqueCite>
				</sinp:Source>
			</sinp:source>
		</sinp:Observation>
	</wfs:member>
</wfs:FeatureCollection>