<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */



/**
 * Default view for the web site (main page).
 * @package views
 */
?>
 <!--[if lte IE 6]>
    <div style='border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative;'>
    <div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display="none"; return false;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-cornerx.jpg' style='border: none;' alt='Close this notice'/></a></div>
    <div style='width: 640px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'>
      <div style='width: 75px; float: left;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-warning.jpg' alt='Warning!'/></div>
      <div style='width: 275px; float: left; font-family: Arial, sans-serif;'>
        <div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>You are using an outdated browser</div>
        <div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>For a better experience using this site, please upgrade to a modern web browser.</div>
      </div>
      <div style='width: 75px; float: left;'><a href='http://www.firefox.com' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-firefox.jpg' style='border: none;' alt='Get Firefox 3.5'/></a></div>
      <div style='width: 75px; float: left;'><a href='http://www.browserforthebetter.com/download.html' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-ie8.jpg' style='border: none;' alt='Get Internet Explorer 8'/></a></div>
      <div style='width: 73px; float: left;'><a href='http://www.apple.com/safari/download/' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-safari.jpg' style='border: none;' alt='Get Safari 4'/></a></div>
      <div style='float: left;'><a href='http://www.google.com/chrome' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-chrome.jpg' style='border: none;' alt='Get Google Chrome'/></a></div>
    </div>
    </div>
    </br></br>
<![endif]-->
<h1>
   <?php  echo $this->translate('Welcome'); ?>
</h1>

<?php
// Get the user
    $userSession = new Zend_Session_Namespace('user');
    $user = $userSession->user;

    // Helper function to display links
    $displayMenuLink = function ($href, $anchor) {
        echo '<li><a href="' . $href . '"  class="pagelink" >' .  $this->translate($anchor) . '</a></li>';
    };

    $displayMenuLinkNewTab = function ($href, $anchor) {
    	echo '<li><a target="_blank" href="' . $href . '"  class="pagelink" rel="noreferrer">' .  $this->translate($anchor) . '</a></li>';
    };

?>
<div class="left-column">
<?php
if (!empty($user)) {
    ?>
    <div class="moduletable_menu">
        <h3><?php echo $this->translate('Select a menu');?></h3>

        <?php
        if ($user->isAllowed('DATA_INTEGRATION') ||
            ($user->isAllowed('DATA_QUERY') && $user->isSchemaAllowed("RAW_DATA")) ||  
            ($user->isAllowed('DATA_EDITION') && $user->isSchemaAllowed("RAW_DATA"))
        ) {

            echo '<h4>' . $this->translate('Source Data') . '</h4>' .
                '<ul class="menu">' ;

            if ($user->isAllowed('DATA_INTEGRATION')) {

               $displayMenuLink(
                    $this->url(array('controller'=>'integration', 'action'=>'show-data-submission-page'), 'default', true),
                    'Manage datasets'

                );
            }
            if ($user->isAllowed('DATA_QUERY') && $user->isSchemaAllowed("RAW_DATA")) {
                $displayMenuLink(
                    $this->url(array('controller'=>'query', 'action'=>'show-query-form'), 'default', true) . '/SCHEMA/RAW_DATA',
                    'Visualize Raw Data'
                );
            }
            echo '</ul>';
        }

        if ($user->isAllowed('DATA_HARMONIZATION') ||
            ($user->isAllowed('DATA_QUERY') && $user->isSchemaAllowed("HARMONIZED_DATA"))
        ) {
            echo '<h4>' . $this->translate('Harmonized Datas') . '</h4>' .
                  '<ul class="menu">' ;
            if ($user->isAllowed('DATA_HARMONIZATION')) {
                $displayMenuLink(
                    $this->url(array('controller' => 'harmonization'), 'default', true),
                    'Data Harmonization'
                );
            }
            if ($user->isAllowed('DATA_QUERY') && $user->isSchemaAllowed("HARMONIZED_DATA")) {
                $displayMenuLink(
                    $this->url(array('controller' => 'query', 'action' => 'show-query-form'), 'default', true) . '/SCHEMA/HARMONIZED_DATA',
                    'Visualize Harmonized Data'
                );
            }
            echo '</ul>';
        }

        if ($user->isAllowed('MANAGE_USERS') || $user->isAllowed('CHECK_CONF')
            || $user->isAllowed('CONFIGURE_METAMODEL')
        ) {
            echo '<h4>' . $this->translate('Administration') . '</h4>' .
                  '<ul class="menu">';
            if ($user->isAllowed('MANAGE_USERS')) {
                $displayMenuLink(
                    $this->url(array('controller'=>'usermanagement'), 'default', true),
                    'User Administration'
                );
            }
            if ($user->isAllowed('CONFIGURE_WEBSITE_PARAMETERS')) {
                $displayMenuLink(
                    $this->url(array('controller'=>'configuration'), 'default', true),
                    'Platform Parameters Configuration'
                );
            }
            if ($user->isAllowed('CHECK_CONF')) {
                $displayMenuLink(
                    $this->url(array('controller'=>'checkconf'), 'default', true),
                    'Check Configuration'
                );
            }
            if ($user->isAllowed('CONFIGURE_METAMODEL')) {
                $displayMenuLink(
                    "/configurateur",
                    'Configure metamodel'
                );
            }
            echo '</ul>';
        }
    ?>
    </div>
    <?php
    }
?>
</div>