services:
    
    # Voters
    ginco.jdd_voter:
        class: Ign\Bundle\GincoBundle\Security\Voter\JddVoter
        tags:
            - { name: security.voter }
        public: false
            
    ginco.submission_voter:
        class: Ign\Bundle\GincoBundle\Security\Voter\SubmissionVoter
        tags:
            - { name: security.voter }
        public: false
        
    ginco.data_voter:
        class: Ign\Bundle\GincoBundle\Security\Voter\DataVoter
        tags:
            - { name: security.voter }
        public: false