# @ annotation for the parent bundle creates problem with routes when adding controller in child bundle
ign_ogam:
    resource: "../../src/Ign/Bundle/OGAMBundle/Controller/"
    type:     annotation
    prefix:   /

ign_ginco:
    resource: "@IgnGincoBundle/Controller/"
    type:     annotation
    prefix:   /