<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */


/**
 * View for the data submission.
 * @package views
 */
?>
<!-- Documentation: http://www.webappers.com/progressBar/ -->
<script type="text/javascript" src="<?php echo $this->baseUrl('js/integration/progressbar.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/integration/later.min.js') ?>"></script>
<!-- jQuery by CDN, with local fallback -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/js/jquery-1.12.4.min.js">\x3C/script>')</script>

<h1>
   <?php echo $this->translate('Manage datasets');?>
</h1>

<p class="onTableLink">
    <a href="<?php echo $this->url(array('controller'=>'integration','action'=>'show-create-data-submission'), null, true) ?>"><?php echo $this->translate('Import a new dataset');?></a>
</p>

<?php
// Get the user permissions
$userSession = new Zend_Session_Namespace('user');
$user = $userSession->user;
?>


<!-- Show the currently active location submissions -->
<?php if(!empty($this->submissions)){ ?>
<table class="sectiontable">
<tr>
    <th style="text-align:center"><?php echo $this->translate('Submission ID');?></th>
    <th style="text-align:center"><?php echo $this->translate('Date');?></th>
    <th style="text-align:center"><?php echo $this->translate('Provider');?></th>
    <th style="text-align:center"><?php echo $this->translate('User');?></th>
    <th style="text-align:center"><?php echo $this->translate('Dataset');?></th>
    <th style="text-align:center"><?php echo $this->translate('Step');?></th>
    <th style="text-align:center"><?php echo $this->translate('Status');?></th>
    <th><?php echo $this->translate('File');?></th>
    <th style="text-align:right"><?php echo $this->translate('Lines');?>&nbsp;</th>
    <?php if ($user->isAllowed('MANAGE_DATASETS')) { ?>
    <th style="text-align:center"><?php echo $this->translate('Export DEE');?>&nbsp;</th>
    <?php } ?>
    <th style="text-align:center"><?php echo $this->translate('Actions');?></th>
    <th></th>
</tr>
<?php
$i = 0;
foreach ($this->submissions as $submission) {
    if ($submission->datasetLabel == null) {
        $submission->datasetLabel = "modèle d'import dépublié";
    }
?>
<tr class="sectiontableentry<?php echo $i % 2?>">
    <td><?php echo  $this->escape($submission->submissionId); ?></td>
    <td><?php echo  $this->escape($submission->date); ?></td>
    <td><?php echo  $this->escape($submission->providerLabel); ?></td>
    <td><?php echo  $this->escape($submission->userLogin); ?></td>
    <td><?php echo  $this->escape($submission->datasetLabel); ?></td>
    <td><?php echo  $this->escape($submission->step); ?></td>
    <td>
        <?php if ($submission->status === "OK" && $submission->step === "INSERT") { ?>
        <!-- occurred when submission is too fast : perform check just after -->
        <script>
            window.onload = function(e){
                window.location="<?php echo  $this->url(array('controller'=>'integration','action'=>'check-submission'), null, true)?>?submissionId=<?php echo $submission->submissionId;?>";
            }
        </script>
        <?php } else if ($submission->status === "OK") { ?>
            <?php echo  $this->escape($submission->status); ?>
            <img src="<?php echo  $this->baseUrl('img/Green_tick.png') ?>" />
        <?php } else if ($submission->status === "WARNING") { ?>
            <?php echo  $this->escape($submission->status); ?>
            <img src="<?php echo  $this->baseUrl('img/warning_orange.png') ?>" />
        <?php } else if ($submission->status === "RUNNING") { ?>
            <div class="tempStatusDiv" id="tempStatusDiv_<?php echo  $submission->submissionId ?>">
            <script type="text/javascript">
                var OgamDesktopIntegration = {};
            // Display the progress bar
            display('progressBar<?php echo  $submission->submissionId ?>', '', 0, '<?php echo  $this->baseUrl('img/') ?>');

            // Refresh The status of the submission
                OgamDesktopIntegration.getStatus_<?php echo $submission->submissionId ?> = function () {
                var url = '<?php echo  $this->baseUrl('Integration/') ?>';
                    <?php if ($submission->step === "CHECK") { ?>
                    url += 'get-check-status';
                    <?php } else { ?>
                    url += 'get-data-status';
                    <?php } ?>
                    OgamDesktopIntegration.request = new XMLHttpRequest();
                    OgamDesktopIntegration.request.onreadystatechange = function () {
                        if (OgamDesktopIntegration.request.readyState == 4) { // 4: request finished and response is ready
                            if (OgamDesktopIntegration.request.status == 200) { // Success
                                var rp = JSON.parse(OgamDesktopIntegration.request.responseText);
                        var src = '<?php echo $this->baseUrl('img/') ?>';
                        switch(rp.status){
                            case 'OK':
                                OgamDesktopIntegration.getStatusTask_<?php echo $submission->submissionId ?>.clear();
                                window.location="<?php echo  $this->url(array('controller'=>'integration','action'=>'check-submission'), null, true)?>?submissionId=<?php echo $submission->submissionId;?>";
                                break;
                            case 'WARNING':
                            case 'ERROR':
                            case 'CRASH':
                                OgamDesktopIntegration.getStatusTask_<?php echo $submission->submissionId ?>.clear();
                                location.reload();
                                break;
                            case 'RUNNING':
                                total = rp.totalCount;
                                if (total == 0) {
                                    percentage = 1;
                                } else {
                                    percentage = rp.currentCount / total;
                                }
                                percentage = (percentage * 100);
                                setLabel('progressBar<?php echo  $submission->submissionId ?>', rp.taskName);
                                setProgress('progressBar<?php echo  $submission->submissionId ?>', percentage);
                                break;
                            default:
                                return;
                            }
                        } else { // Failure

                        }
                    }
                };
                OgamDesktopIntegration.request.open("GET", url+'?action=status&submissionId='+<?php echo $submission->submissionId ?>, true);
                OgamDesktopIntegration.request.send();
            }
            OgamDesktopIntegration.getStatusTask_<?php echo $submission->submissionId ?> = later.setInterval(OgamDesktopIntegration.getStatus_<?php echo $submission->submissionId ?>, later.parse.text('every 2 sec'));
            </script>
            </div>
        <?php } else { //"ERROR" or "CRASH") ?>
            <?php echo $this->escape($submission->status); ?>
            <img src="<?php echo  $this->baseUrl('img/Red_x.png') ?>" />
        <?php } ?>
    </td>
    <td colspan=2>
        <?php if ($submission->status !== "DATARUNNING") : ?>
            <table width="100%">
            <?php foreach ($submission->files as $file) : ?>
                <tr><td class="file-name">
                	<span title="<?php echo  $file->fileType ?>">
                    <?php
                        $fileName = $file->fileName;
                        $fileName = strtr($fileName,'\\','/');
                        $fileName = substr($fileName, strrpos($fileName,'/') + 1);
                        echo $fileName;
                    ?>
                    </span>
                </td>
                <td class="line-number"><?php echo  $file->lineNumber ?></td>
                </tr>

            <?php endforeach; ?>
            </table>
        <?php endif; ?>
    </td>

    <?php if ($user->isAllowed('MANAGE_DATASETS')) { ?>
    <td><!-- Export cell -->
        <?php
        if ($submission->status != "OK" || $submission->step != "VALIDATE") {
        ?>
        <p>Publiez les données <br>pour les exporter en DEE.</p>
        <?php } else { ?>

        <div class="dee-status hidden" data-target="<?php echo $submission->submissionId ?>"></div>
        <div class="progress hidden">
            <script type="text/javascript">
                var $label = "<?php echo 'Génération DEE ' . (($submission->status == 'RUNNING') ? 'en cours...' : 'en attente...')?>";
                display('deeprogress' + <?php echo $submission->submissionId ?>, $label, 0 ,'/img/');
            </script>
        </div>
        <div class="dee-content" data-target="<?php echo $submission->submissionId ?>"></div>
        <?php } ?>
    </td><!-- End of the export cell -->
    <?php } ?>

    <!-- Actions cell -->
    <td>
    <?php
	if ($submission->step === "INSERT" && $submission->status === "OK") {
?>
    <p><a href="<?php echo  $this->url(array('controller'=>'integration','action'=>'check-submission'), null, true)?>?submissionId=<?php echo $submission->submissionId;?>" ><?php echo $this->translate('Check data');?></a></p>
    <?php }
	if ($submission->step !== "INIT" && $submission->status !== "DATARUNNING") {
?>
    <p><a href="<?php echo  $this->url(array('controller'=>'proxy','action'=>'showreport'), 'default', true)?>?submissionId=<?php echo $submission->submissionId;?>" ><?php echo $this->translate('Show report');?></a></p>
    <?php }
    if ($submission->step === "CHECK" && ($submission->status === "OK" || $submission->status === "WARNING") && $user->isAllowed('CONFIRM_SUBMISSION')) {
?>
    <p><a href="<?php echo  $this->url(array('controller'=>'integration','action'=>'validate-data'), null, true)?>?submissionId=<?php echo $submission->submissionId;?>" onClick="return confirm('<?php echo $this->translate('Confirm_submission_warning');?>');"><?php echo $this->translate('Publish data');?></a></p>
    <?php
    }
    if ($submission->step === "VALIDATE" && ($submission->status === "OK" || $submission->status === "WARNING") && $user->isAllowed('CONFIRM_SUBMISSION')) {
    ?>
    <p><a href="<?php echo  $this->url(array('controller'=>'integration','action'=>'invalidate-data'), null, true)?>?submissionId=<?php echo $submission->submissionId;?>" onClick="return confirm('<?php echo $this->translate('Unpublish_submission_warning');?>');"><?php echo $this->translate('Unpublish data');?></a></p>
    <?php
    }
    if ($submission->status === "OK") {
        ?>
        <p>
            <a href="<?php echo $this->url(array('controller' => 'integration', 'action' => 'export-sensibility-report'), null, true) ?>?submissionId=<?php echo $submission->submissionId; ?>"><?php echo $this->translate('Sensibility Report'); ?></a>
        </p>
    <?php
    }
    if ($submission->step != "VALIDATE" || $user->isAllowed('CANCEL_VALIDATED_SUBMISSION')) {
        if ($submission->providerId == $userSession->user->provider->id || ($user->isAllowed('CANCEL_OTHER_PROVIDER_SUBMISSION'))) {
?>
    <p><a href="<?php echo  $this->url(array('controller'=>'integration','action'=>'cancel-data-submission'), null, true)?>?submissionId=<?php echo $submission->submissionId;?>" onClick="return confirm('<?php echo $this->translate('Are you sure?');?>');"><?php echo $this->translate('Cancel Submission');?></a></p>
<?php  }
    } ?>
    </td>
    <!-- End of the actions cell -->
</tr>
<?php
	$i++;
}
?>
</table>
<?php } else { ?>
<div class="no-submission"><?php echo $this->translate('No submission found');?></div>
<?php } ?>


<!-- Scripts of the page -->
<script type="text/javascript">

function updateStatusAndContent($submissionId, $status = null) {
    console.log('updateStatusAndContent, taskId:',$submissionId, 'status', $status);
    if ( $status ) {
        updateStatusDiv($submissionId, $status);
        updateContentDiv($submissionId, $status);
    }
    else {
        $.getJSON("/gmlexport/get-status", {
            submissionId: $submissionId
        }, function (data) {
            console.log(data);
            updateStatusDiv($submissionId, data.status);
            updateContentDiv($submissionId, data.status, data.progress);
        });
    }
}


function updateStatusDiv( $submissionId, $status) {
    var $statusDiv = $("div.dee-status[data-target='" + $submissionId + "']");
    // Update status
    $statusDiv.html($status);
}


function updateContentDiv($submissionId, $status, $progress = 0) {
    var $contentDiv = $("div.dee-content[data-target='" + $submissionId + "']");

    var $actions = getActions($status);
    // console.log($actions);

    $contentDiv.html('');

    if ($status == 'COMPLETED') {
        var $downloadLink = $("<a class='align_images' href='/gmlexport/download?submissionId=" + $submissionId+ "'><img src='/img/save.png'> Télécharger les DEE</a>");
        $contentDiv.append($downloadLink);
    }

    // Update progress bar if RUNNING
    var $progressBar = $contentDiv.parent().find('div.progress');
    if ($status == 'RUNNING' || $status == 'PENDING') {
        if ($progressBar.hasClass('hidden')) {
            $progressBar.removeClass('hidden');
        }
        var $label = 'Génération DEE ' + (($status == 'RUNNING') ? 'en cours...' : 'en attente...');
        setLabel('deeprogress' + $submissionId, $label);
        setProgress('deeprogress' + $submissionId, $progress);
    }
    // If not RUNNING remove progress bar
    else {
        $progressBar.addClass('hidden');
    }

    if ($.inArray( 'Lancer', $actions ) != -1) {
        var $launchLink = $("<a class='align_images' href=''><img src='/img/play.png'> Générer les DEE</a>");
        $contentDiv.append($launchLink);
        $launchLink.click( function(e) {
            e.preventDefault();
            addExportJob($submissionId);
        });
    }
    if ($.inArray( 'Annuler', $actions ) != -1) {
        var $cancelLink = $("<a class='align_images' href=''><img src='/img/delete.png'> Annuler</a>");
        $contentDiv.append($cancelLink);
        $cancelLink.click( function(e) {
            e.preventDefault();
            cancelExport($submissionId);
        });
    }
    if ($.inArray( 'Relancer', $actions ) != -1) {
        var $launchAgainLink = $("<a class='align_images' href=''><img src='/img/refresh.png'> Regénérer</a>");
        $contentDiv.append($launchAgainLink);
        $launchAgainLink.click( function(e) {
            e.preventDefault();
            addExportJob($submissionId);
        });
    }
    // Wrap each link in a div
    $contentDiv.find( "a" ).wrap( "<div class='action'></div>" );
}

function getActions($status) {
    var $actions = [];
    switch ($status) {
        case 'NOT FOUND':
            $actions = ['Lancer'];
            break;
        case 'PENDING':
        case 'RUNNING':
            $actions = ['Annuler'];
            break;
        case 'COMPLETED':
        case 'ERROR':
        case 'ABORTED':
            $actions = ['Relancer', 'Annuler'];
            break;
        default:
            $actions = ['Lancer', 'Annuler'];
            break;
    }
    return $actions;
}

function addExportJob($submissionId) {
    $.getJSON( "/gmlexport/add-job", {
        submissionId: $submissionId
    },function( data ) {
        if (data.success) {
            updateStatusAndContent($submissionId, data.status);
        }
    });
}


function cancelExport($submissionId) {
    $.getJSON( "/gmlexport/cancel-export", {
        submissionId: $submissionId
    },function( data ) {
         if (data.success) {
            updateStatusAndContent($submissionId, data.status);
        }
    });
}

function updateAllPendingAndRunningTasks() {
    var $submissionIds = [];
    $('.dee-status').each(function() {
        if ( $(this).html() == 'RUNNING' || $(this).html() == 'PENDING' ) {
            $submissionIds.push($(this).attr('data-target'));
        }
    });

    if ($submissionIds.length) {
        $.getJSON("/gmlexport/get-all-status", {
            submissionIds: $submissionIds
        }, function (data) {
            console.log(data);
            $.each(data, function (index, value) {
                updateStatusDiv(value.submissionId, value.status);
                updateContentDiv(value.submissionId, value.status, value.progress);
            });
        });
    }
}

jQuery(document).ready(function() {

    $('.dee-content').each(function() {
        var $submissionId = $(this).attr('data-target');
        updateStatusAndContent($submissionId);
    });

    // Update progress for running scripts
    var timerId = setInterval( updateAllPendingAndRunningTasks , 1000);

});

</script>

