<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */


/**
 * View for the datasets (jdd).
 * Completely modified with #801.
 * @package views
 */
?>
<!-- Documentation: http://www.webappers.com/progressBar/ -->
<script type="text/javascript" src="<?php echo $this->baseUrl('js/integration/progressbar.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/integration/later.min.js') ?>"></script>
<!-- jQuery by CDN, with local fallback -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/js/jquery-1.12.4.min.js">\x3C/script>')</script>

<h1>
   <?php echo $this->translate('Manage datasets');?>
</h1>

<p class="onTableLink">
    <a href="<?php echo $this->url(array('controller'=>'integration','action'=>'show-create-jdd-page'), null, true) ?>"><?php echo $this->translate('Import a new dataset');?></a>
    |
    <a class='align_images' href="<?php echo $this->url(array('controller'=>'integration','action'=>'download-active-submissions-csv'), null, true) ?>"><img src='/img/save.png'> <?php echo $this->translate('Download submissions list');?></a>
</p>

<?php
// Get the user permissions
$userSession = new Zend_Session_Namespace('user');
$user = $userSession->user;
?>


<!-- Show the currently active location submissions -->
<?php if(!empty($this->datasets)){ ?>
    <table class="sectiontable">
        <tr class="sectiontableheader">
            <th><?php echo $this->translate('ID');?></th>
            <th><?php echo $this->translate('Update');?></th>
            <th><?php echo $this->translate('Title');?></th>
            <th><?php echo $this->translate('Provider');?></th>
            <th><?php echo $this->translate('Nb of data');?></th>
            <th><?php echo $this->translate('DSR');?></th>
            <th><?php echo $this->translate('Reports');?></th>
            <?php if ($user->isAllowed('MANAGE_DATASETS')) { ?>
                <th><?php echo $this->translate('DEE');?>&nbsp;</th>
            <?php } ?>
            <th><?php echo $this->translate('Delete');?></th>
        </tr>
    <?php
        $i = 0;
        foreach ($this->datasets as $dataset) {
            $hasSubmission = isset($dataset['submission_id']);
            $hasExportFile = isset($dataset['export_file_id']);?>
            <tr class="sectiontableentry<?php echo $i % 2?>">
                <td title="<?php echo $this->escape($dataset['submission_id_tooltip']);?>&#013;<?php echo $this->escape($dataset['jdd_metadata_id_tooltip']);?>"><?php if($hasSubmission && $dataset['step'] !== "CANCEL") {
                        echo $this->escape($dataset['submission_id']);
                }?><br/>
                <?php echo $this->escape($dataset['jdd_metadata_id_short']); ?></td>
                <td><?php echo  $this->escape($dataset['created_at']); ?></td>
                <td title="<?php echo $this->escape($dataset['title']); ?>"><?php echo $this->escape($dataset['title_short']); ?></td>
                <td style="text-align:center"><?php echo $this->escape($dataset['provider_label']);?></td>
                <td style="text-align:center"><?php echo $this->escape($dataset['nb_data']);?></td>
                <!-- Begin DSR column  -->
                <td>
                    <table>
                        <tr>
                        <?php
                            if($hasSubmission){
                                if ($dataset['step'] === "CANCEL") {?>
                                    <td><img title="<?php echo $this->translate('Upload data to publish them');?>" src="<?php echo $this->baseUrl('img/play_publish_grey.png') ?>"></td>
                                    <td><a href="<?php echo $this->url(array('controller'=>'integration','action'=>'show-create-data-submission'), null, true)?>?jddId=<?php echo $dataset['id'];?>">
                                    <img title="<?php echo $this->translate('Upload data file');?>" src="<?php echo $this->baseUrl('img/upload.png') ?>"/></a></td>
                                    <td title="<?php echo $this->translate('You have to upload data to delete it');?>"><img src="<?php echo $this->baseUrl('img/delete_x_icon_grey.png') ?>"></td><?php
                                }
                                if ($dataset['step'] === "INIT") {?>
                                <!--Publish, unpublish or warning icons -->
                                    <td><img title="<?php echo $this->translate('Upload data to publish them');?>" src="<?php echo $this->baseUrl('img/play_publish_grey.png') ?>"></td>
                                    <td><a href="<?php echo $this->url(array('controller'=>'integration','action'=>'show-create-data-submission'), null, true)?>?jddId=<?php echo $dataset['id'];?>">
                                    <img title="<?php echo $this->translate('Upload data file');?>" src="<?php echo $this->baseUrl('img/upload.png') ?>"/></a></td><?php
                                    if ($user->isAllowed('CANCEL_VALIDATED_SUBMISSION')) {
                                        if ($dataset['provider_id'] == $userSession->user->provider->id
                                            || $user->isAllowed('CANCEL_OTHER_PROVIDER_SUBMISSION')) {?>
                                            <td><a href="<?php echo $this->url(array('controller'=>'integration','action'=>'cancel-data-submission'), null, true)?>?submissionId=<?php echo $dataset['submission_id'];?>&jddId=<?php echo $dataset['id'];?>"
                                            onClick="return confirm('<?php echo $this->translate('Do you really want to delete this submission?');?>');"
                                            title = "<?php echo $this->translate('Cancel Submission');?>">
                                            <img src="<?php echo $this->baseUrl('img/delete_x_icon.png'); ?>" /></a></td><?php
                                        }
                                    }
                                } else if ($dataset['step'] === "INSERT") {
                                    if ($dataset['status'] === "OK") {?>
                                        <!-- occurred when submission is too fast : perform check just after -->
                                        <script>
                                            window.onload = function(e){
                                                window.location="<?php echo  $this->url(array('controller'=>'integration','action'=>'check-submission'), null, true)?>?submissionId=<?php echo $dataset['submission_id'];?>";
                                            }
                                        </script><?php
                                    } else if ($dataset['status'] === "WARNING") {
                                        echo $this->escape($dataset['status']); ?>
                                        <img src="<?php echo $this->baseUrl('img/warning_orange.png') ?>"/><?php
                                    } else if ($dataset['status'] === "RUNNING"){ ?>
                                        <div class="tempStatusDiv" id="tempStatusDiv_<?php echo $dataset['submission_id'] ?>">
                                        <script type="text/javascript">
                                            var OgamDesktopIntegration = {};
                                            // Display the progress bar
                                            display('progressBar<?php echo  $dataset['submission_id'] ?>', '', 0, '<?php echo  $this->baseUrl('img/') ?>');
                                            // Refresh The status of the submission
                                            OgamDesktopIntegration.getStatus_<?php echo $dataset['submission_id'] ?> = function () {
                                                var url = '<?php echo  $this->baseUrl('Integration/') ?>';
                                                <?php
                                                if ($dataset['step'] === "CHECK") { ?>
                                                    url += 'get-check-status';
                                                <?php
                                                } else { ?>
                                                    url += 'get-data-status';
                                                <?php
                                                } ?>
                                                OgamDesktopIntegration.request = new XMLHttpRequest();
                                                OgamDesktopIntegration.request.onreadystatechange = function () {
                                                    if (OgamDesktopIntegration.request.readyState == 4) { // 4: request finished and response is ready
                                                        if (OgamDesktopIntegration.request.status == 200) { // Success
                                                            var rp = JSON.parse(OgamDesktopIntegration.request.responseText);
                                                            var src = '<?php echo $this->baseUrl('img/') ?>';
                                                            switch(rp.status){
                                                                case 'OK':
                                                                    OgamDesktopIntegration.getStatusTask_<?php echo $dataset['submission_id'] ?>.clear();
                                                                    window.location="<?php echo  $this->url(array('controller'=>'integration','action'=>'check-submission'), null, true)?>?submissionId=<?php echo $dataset['submission_id'];?>&jddId=<?php echo $dataset['id'];?>";
                                                                    break;
                                                                case 'WARNING':
                                                                case 'ERROR':
                                                                case 'CRASH':
                                                                    OgamDesktopIntegration.getStatusTask_<?php echo $dataset['submission_id'] ?>.clear();
                                                                    location.reload();
                                                                    break;
                                                                case 'RUNNING':
                                                                    total = rp.totalCount;
                                                                    if (total == 0) {
                                                                        percentage = 1;
                                                                    } else {
                                                                        percentage = rp.currentCount / total;
                                                                    }
                                                                    percentage = (percentage * 100);
                                                                    setLabel('progressBar<?php echo  $dataset['submission_id'] ?>', rp.taskName);
                                                                    setProgress('progressBar<?php echo  $dataset['submission_id'] ?>', percentage);
                                                                    break;
                                                                default:
                                                                    return;
                                                            }
                                                        } else {
                                                            // Failure
                                                        }
                                                    }
                                                };
                                                OgamDesktopIntegration.request.open("GET", url+'?action=status&submissionId='+<?php echo $dataset['submission_id'] ?>, true);
                                                OgamDesktopIntegration.request.send();
                                            }
                                            OgamDesktopIntegration.getStatusTask_<?php echo $dataset['submission_id'] ?> = later.setInterval(OgamDesktopIntegration.getStatus_<?php echo $dataset['submission_id'] ?>, later.parse.text('every 2 sec'));
                                        </script>
                                        </div><?php
                                    } else if ($dataset['status'] === 'ERROR' || $dataset['status'] === 'CRASH') {?>
                                        <td><img title="<?php echo $this->translate('The file contains errors')?>" src="<?php echo $this->baseUrl('img/warning_red.png') ?>"/></td>
                                        <td><a href="<?php echo $this->url(array('controller'=>'integration','action'=>'show-create-data-submission'), null, true)?>?jddId=<?php echo $dataset['id'];?>">
                                            <img title="<?php echo $this->translate('Upload data file');?>" src="<?php echo $this->baseUrl('img/upload.png') ?>"/></a></td><?php
                                         if ($dataset['provider_id'] == $userSession->user->provider->id
                                         || $user->isAllowed('CANCEL_OTHER_PROVIDER_SUBMISSION')) {?>
                                             <td><a href="<?php echo $this->url(array('controller'=>'integration','action'=>'cancel-data-submission'), null, true)?>?submissionId=<?php echo $dataset['submission_id'];?>&jddId=<?php echo $dataset['id'];?>"
                                                    onClick="return confirm('<?php echo $this->translate('Do you really want to delete this submission?');?>');"
                                                    title="<?php echo $this->translate('Cancel Submission');?>">
                                                 <img src="<?php echo $this->baseUrl('img/delete_x_icon.png'); ?>" /></a></td><?php
                                         }
                                    }
                                } else if ($dataset['step'] === "CHECK") {
                                    if(($dataset['status'] === "OK" || $dataset['status'] === "WARNING") && $user->isAllowed('CONFIRM_SUBMISSION')){?>
                                    <td><a href="<?php echo  $this->url(array('controller'=>'integration','action'=>'validate-data'), null, true)?>?submissionId=<?php echo $dataset['submission_id'];?>"
                                       onClick="return confirm('<?php echo $this->translate('Confirm_submission_warning');?>');"
                                       title="<?php echo $this->translate('Publish data');?>">
                                    <img src="<?php echo $this->baseUrl('img/play_publish.png'); ?>"/></a></td>
                                    <td><a href="<?php echo $this->url(array('controller'=>'integration','action'=>'show-create-data-submission'), null, true)?>?jddId=<?php echo $dataset['id'];?>">
                                            <img title="<?php echo $this->translate('Upload data file');?>" src="<?php echo $this->baseUrl('img/upload.png') ?>"/></a></td><?php
                                        if ($dataset['provider_id'] == $userSession->user->provider->id
                                            || $user->isAllowed('CANCEL_OTHER_PROVIDER_SUBMISSION')) {?>
                                            <td><a href="<?php echo $this->url(array('controller'=>'integration','action'=>'cancel-data-submission'), null, true)?>?submissionId=<?php echo $dataset['submission_id'];?>&jddId=<?php echo $dataset['id'];?>"
                                             onClick="return confirm('<?php echo $this->translate('Do you really want to delete this submission?');?>');"
                                             title = "<?php echo $this->translate('Cancel Submission');?>">
                                            <img src="<?php echo $this->baseUrl('img/delete_x_icon.png'); ?>"/></a></td><?php
                                        }
                                    } else if($dataset['status'] === "RUNNING") {?>
                                        <td><img title="<?php echo $this->translate('Upload data to publish them');?>" src="<?php echo $this->baseUrl('img/play_publish_grey.png') ?>"></td>
                                        <td title="<?php echo $this->translate('You cannot upload while an insert is going on');?>"><img src="<?php echo $this->baseUrl('img/upload_grey.png') ?>"></td>
                                        <td title="<?php echo $this->translate('You have to upload data to delete it');?>"><img src="<?php echo $this->baseUrl('img/delete_x_icon_grey.png') ?>"></td><?php
                                    }  else if($dataset['status'] === "ERROR") {?>
                                        <td><img title="<?php echo $this->translate('The file contains errors')?>" src="<?php echo $this->baseUrl('img/warning_red.png') ?>" /></td>
                                        <td><a href="<?php echo $this->url(array('controller'=>'integration','action'=>'show-create-data-submission'), null, true)?>?jddId=<?php echo $dataset['id'];?>">
                                            <img title="<?php echo $this->translate('Upload data file');?>" src="<?php echo $this->baseUrl('img/upload.png') ?>"/></a></td><?php
                                        if ($dataset['provider_id'] == $userSession->user->provider->id
                                            || $user->isAllowed('CANCEL_OTHER_PROVIDER_SUBMISSION')) {?>
                                            <td><a href="<?php echo $this->url(array('controller'=>'integration','action'=>'cancel-data-submission'), null, true)?>?submissionId=<?php echo $dataset['submission_id'];?>&jddId=<?php echo $dataset['id'];?>"
                                             onClick="return confirm('<?php echo $this->translate('Do you really want to delete this submission?');?>');"
                                             title = "<?php echo $this->translate('Cancel Submission');?>">
                                            <img src="<?php echo $this->baseUrl('img/delete_x_icon.png'); ?>" /></a></td><?php
                                        }
                                    }
                                } else if ($dataset['step'] === "VALIDATE") {
                                    if(($dataset['status'] === "OK" || $dataset['status'] === "WARNING") && $user->isAllowed('CONFIRM_SUBMISSION')) {?>
                                        <td><a href="<?php echo  $this->url(array('controller'=>'integration','action'=>'invalidate-data'), null, true)?>?submissionId=<?php echo $dataset['submission_id'];?>"
                                               onClick="return confirm('<?php echo $this->translate('Unpublish_submission_warning');?>');"
                                               title="<?php echo $this->translate('Unpublish data');?>">
                                            <img src="<?php echo  $this->baseUrl('img/stop_green.png'); ?>" /></a></td>
                                        <td title="<?php echo $this->translate('You have to unpublish the data to reupload');?>"><img src="<?php echo $this->baseUrl('img/upload_grey.png') ?>"></td>
                                        <td title="<?php echo $this->translate('You have to unpublish the data to delete it');?>"><img src="<?php echo $this->baseUrl('img/delete_x_icon_grey.png') ?>"></td><?php
                                    }
                                }
                            }?>
                        </tr>
                    </table>
                </td>
                <!-- End DSR column  -->
                <!-- Begin reports column -->
                <td style="text-align:center">
                <?php
                    if($hasSubmission){
                        if ($dataset['step'] !== "CANCEL") {?>
                        <select onChange="window.location.href=this.value">
                            <option value="">
                                <?php echo '---' . $this->translate('Download reports') . '---';?>
                            </option>
                            <?php
                            if ($dataset['step'] !== "INIT" && $dataset['status'] !== "DATARUNNING") {?>
                                <option value="<?php echo $this->url(array('controller'=>'dataset','action'=>'download-report'), 'default', true) ?>?submissionId=<?php echo $dataset['submission_id']; ?>&report=integrationReport">
                                               <?php echo $this->translate('Conformity and consistency');?>
                                </option>
                            <?php
                            }
                            if ($dataset['status'] === "OK") {?>
                                <option value="<?php echo $this->url(array('controller' => 'dataset', 'action' => 'download-report'), 'default', true) ?>?submissionId=<?php echo $dataset['submission_id']; ?>&report=sensibilityReport">
                                               <?php echo $this->translate('Sensibility'); ?>
                                </option>
                                <option value="<?php echo $this->url(array('controller' => 'dataset', 'action' => 'download-report'), 'default', true) ?>?submissionId=<?php echo $dataset['submission_id']; ?>&report=permanentIdsReport">
                                               <?php echo $this->translate('Permanent Ids'); ?>
                                </option>
                            <?php
                            }
                        } else {
                            echo '-';
                        }
                     }?>
                    </select>
                </td>
                <!-- End reports column -->
                <!-- Begin DEE column -->
                <td style="text-align:center">
                <?php
                     if($hasSubmission) {
                         if ($user->isAllowed('MANAGE_DATASETS')) {
                             if (($dataset['status'] == "OK" && $dataset['step'] == "CHECK") && !$hasExportFile) {?>
                             <table><tr>
                                 <td title="<?php echo $this->translate('Publish the data to export them as DEE');?>"><img src="<?php echo $this->baseUrl('img/play_publish_grey.png') ?>"></td>
                                 <td title="<?php echo $this->translate('Publish the data to download the DEE');?>"><img src="<?php echo $this->baseUrl('img/download_grey.png') ?>"></td>
                                 <td title="<?php echo $this->translate('Generate the DEE to delete it');?>"><img src="<?php echo $this->baseUrl('img/delete_x_icon_grey.png') ?>"></td>
                                 </tr></table><?php
                             } else if (($dataset['status'] == "OK" && $dataset['step'] == "VALIDATE") && !$hasExportFile) {?>
                             <div class="dee-status hidden" data-export-file-id="-1" data-jdd-id="<?php echo $dataset['id']?>"></div>
                                 <div class="progress hidden">
                                     <script type="text/javascript">
                                         var $label = "<?php echo 'Génération DEE ' . (($dataset['status'] == 'RUNNING') ? 'en cours...' : 'en attente...')?>";
                                         display('deeprogress' + <?php echo $dataset['id'] ?>, $label, 0 ,'/img/');
                                     </script>
                                 </div>
                                 <div class="dee-content" data-submission-step="<?php echo $dataset['step']?>"
                                      data-export-file-id="-1" data-jdd-id="<?php echo $dataset['id']?>"></div><?php
                             }
                             else if (($dataset['status'] == "OK" && $dataset['step'] == "VALIDATE") || $hasExportFile) {?>
                             <div class="dee-status hidden" data-export-file-id="<?php echo $dataset['export_file_id']?>"
                             data-jdd-id="<?php echo $dataset['id']?>"></div>
                                 <div class="progress hidden">
                                     <script type="text/javascript">
                                         var $label = "<?php echo 'Génération DEE ' . (($dataset['status'] == 'RUNNING') ? 'en cours...' : 'en attente...')?>";
                                         display('deeprogress' + <?php echo $dataset['id'] ?>, $label, 0 ,'/img/');
                                     </script>
                                 </div>
                                 <div class="dee-content" data-submission-step="<?php echo $dataset['step']?>"
                                      data-export-file-id="<?php echo $dataset['export_file_id']?>" data-jdd-id="<?php echo $dataset['id']?>"></div><?php
                             } else {?>
                                 <table><tr>
                                 <td title="<?php echo $this->translate('Publish the data to export them as DEE');?>"><img src="<?php echo $this->baseUrl('img/play_publish_grey.png') ?>"></td>
                                 <td title="<?php echo $this->translate('Publish the data to download the DEE');?>"><img src="<?php echo $this->baseUrl('img/download_grey.png') ?>"></td>
                                 <td title="<?php echo $this->translate('Generate the DEE to delete it');?>"><img src="<?php echo $this->baseUrl('img/delete_x_icon_grey.png') ?>"></td>
                                 </tr></table><?php
                             }
                         }
                     }?>
                </td>
                <!-- End DEE column  -->
                <!-- Begin remove column -->
                <td style="text-align:center">
                    <?php
                    if($hasSubmission && !$hasExportFile){
                        if ($dataset['step'] === "CANCEL" && !isset($dataset['export_file_id'])) {
                            if ($dataset['provider_id'] == $userSession->user->provider->id||($user->isAllowed('CANCEL_OTHER_PROVIDER_SUBMISSION'))) {?>
                                <a href="<?php echo $this->url(array('controller'=>'integration','action'=>'remove-jdd'), null, true)?>?jddId=<?php echo $dataset['id'];?>"
                                   onClick="return confirm('<?php echo $this->translate('Do you really want to delete this dataset?');?>');" style="text-align:center"
                                   title="<?php echo $this->translate('Remove dataset');?>">
                                    <img src="<?php echo $this->baseUrl('img/delete_x_icon.png') ?>"/>
                                </a>
                                <?php
                            }
                        } else {?>
                            <img title="<?php echo $this->translate('The dataset can be deleted only if it not contains DSR and DEE');?>"
                                 src="<?php echo $this->baseUrl('img/delete_x_icon_grey.png') ?>">
                             <?php
                        }
                    } else if (!$hasSubmission && !$hasExportFile) {?>
                        <a style="text-align:center" href="<?php echo $this->url(array('controller'=>'integration','action'=>'remove-jdd'), null, true)?>?jddId=<?php echo $dataset['id'];?>"
                           onClick="return confirm('<?php echo $this->translate('Do you really want to delete this dataset?');?>');"
                           title="<?php echo $this->translate('Remove dataset');?>">
                           <img src="<?php echo $this->baseUrl('img/delete_x_icon.png') ?>"/>
                        </a>
                        <?php
                    } else {?>
                        <img title="<?php echo $this->translate('The dataset can be deleted only if it not contains DSR and DEE');?>"
                        src="<?php echo $this->baseUrl('img/delete_x_icon_grey.png') ?>">
                        <?php
                    }?>
                </td>
                <!-- End remove column -->
            </tr>
            <?php
            $i++;
        }?>
    </table>
   
   <!-- DEE regeneration popup -->
	<div id="dialogoverlay"></div>
	<div id="dialogbox">
	  <div>
	    <div id="dialogboxhead"></div>
	    <div id="dialogboxbody">
	    </div>
	    <div id="dialogboxfoot"></div>
	  </div>
	</div>

    <?php
} else { ?>
    <div class="no-submission"><?php echo $this->translate('No dataset found');?></div>
<?php
} ?>

<!-- Scripts of the page -->
<script type="text/javascript">
/**
 * Scripts for DEE Export management
 * Actions are sent via Ajax, and get back status of the export job.
 * Status are:
 * - NOT FOUND: no export initiated
 * - PENDING: export initiated, but not running yet
 * - RUNNING: in progess
 * - COMPLETED: done, export file is available
 * - ABORTED: problem during export, file is not available
 */

 
/**
 * Custom prompt to get user comment when generating DEE
 */
function CustomPrompt(){
	this.render = function(jddId, exportFileId, deeDialogTitle, deeDialog, deeAction){
		var dialogoverlay = document.getElementById('dialogoverlay');
	    var dialogbox = document.getElementById('dialogbox');
		dialogoverlay.style.display = "block";
	    dialogbox.style.display = "block";
	    document.getElementById('dialogboxhead').innerHTML = deeDialogTitle;
	    document.getElementById('dialogboxbody').innerHTML = deeDialog;
		document.getElementById('dialogboxfoot').innerHTML = '<button onclick="Prompt.check_empty(\''+jddId+'\', \''+exportFileId+'\', \''+deeAction+'\')">Valider</button> <button onclick="Prompt.cancel()">Annuler</button>';
	}
	this.cancel = function(){
		document.getElementById('dialogbox').style.display = "none";
		document.getElementById('dialogoverlay').style.display = "none";
	}
	this.ok = function(jddId, exportFileId, deeAction){
		var comment = document.getElementById('prompt_comment').value;
		if (deeAction != 'delete') {
			addExportJob(jddId, exportFileId, deeAction, comment);
		} else {
            cancelExport(jddId, exportFileId, comment);
		}
		document.getElementById('dialogbox').style.display = "none";
		document.getElementById('dialogoverlay').style.display = "none";
	}
	this.check_empty = function(jddId, exportFileId, deeAction){
		if (document.getElementById('prompt_comment').value == "" && deeAction != 'create') {
			alert("Vous n'avez pas laissé de commentaire !");
		} else if (document.getElementById('prompt_comment').value.length > 6000) {
			alert("Votre commentaire ne doit pas dépasser 6000 caractères.");
		} else {
			Prompt.ok(jddId, exportFileId, deeAction);
		}
	}
	
}
Prompt = new CustomPrompt();


/**
 * Update status and content divs for given submission.
 * If status is not given, launch a ajax request to get it.
 *
 * @param $jddId
 * @param $exportFileId
 * @param $status
 */
function updateStatusAndContent($jddId, $exportFileId, $status = null) {
    if ($status) {
        updateStatusDiv($jddId, $exportFileId, $status);
        updateContentDiv($jddId, $exportFileId, $status);
    }
    else {
        if($exportFileId >= 0){
            $.getJSON("/gmlexport/get-status", {
                submissionId: $exportFileId,
            }, function (data) {
                updateStatusDiv($jddId, $exportFileId, data.status);
                updateContentDiv($jddId, $exportFileId, data.status, data.progress);
            });

        } else {
            updateStatusDiv($jddId, $exportFileId, 'NOT FOUND');
            updateContentDiv($jddId, $exportFileId, 'NOT FOUND', 0);
        }
    }
}

/**
 * Search all PENDING and RUNNING jobs (by the content of the hidden status div)
 * And launch a ajax request to retrieve their status and progress
 * Then update status and content divs.
 */
function updateAllPendingAndRunningTasks() {
    var $exportFileIds = [];
    var $jddIds = [];
    $('.dee-status').each(function() {
        if ( $(this).html() == 'RUNNING' || $(this).html() == 'PENDING' ) {
            $exportFileId = $(this).attr('data-export-file-id');
            $exportFileIds.push($exportFileId);
            $jddId = $(this).attr('data-jdd-id');
            $jddIds.push($jddId);
        }
    });

    if ($exportFileIds.length) {
        $.getJSON("/gmlexport/get-all-status", {
            submissionIds: $exportFileIds,
            jddIds: $jddIds
        }, function (data) {
            $.each(data, function (index, value) {
                updateStatusDiv(value.jddId, value.submissionId, value.status);
                updateContentDiv(value.jddId, value.submissionId, value.status, value.progress);
            });
        });
    }
}

/**
 * Update status div alone.
 * The status div is hidden with css, and is used by the scripts
 * to know if there is PENDING or RUNNING jobs (needing to ask periodically for their status)
 *
 * @param $exportFileId
 * @param $status
 */
function updateStatusDiv($jddId, $exportFileId, $status) {
    var $statusDiv = $("div.dee-status[data-jdd-id='" + $jddId + "']");
    // Update status
    $statusDiv.html($status);
}

/**
 * Update content div alone.
 * The content div is visible and shows:
 *  - the download link when available
 *  - the progress bar when the export job is running
 *  - action links: launch, cancel, relaunch
 *
 * @param $jddId
 * @param $exportFileId
 * @param $status
 * @param $progress
 */
function updateContentDiv($jddId, $exportFileId, $status, $progress = 0) {
    var $contentDiv = $("div.dee-content[data-jdd-id='" + $jddId + "']");
    var $submissionStep = $contentDiv.attr('data-submission-step');
    var $exportFileId = $contentDiv.attr('data-export-file-id');
    var $actions = getActions($status);

    $contentDiv.html('');
    var table = $('<table></table>');
    var row = $('<tr style="text-align:center"></tr>');
    table.append(row);

    // Action links
    if ($.inArray( 'Lancer', $actions ) != -1) {
        var $launchLink = $("<td><a title='Générer la DEE' href=''><img src='/img/play_publish.png'></a></td>");
        row.append($launchLink);
        $launchLink.click( function(e) {
            e.preventDefault();
            var deeDialogTitle = "Génération d'une DEE";
            var deeDialog = "<p>Vous allez générer une DEE. Une notification va être envoyée à la plateforme nationale,";
            deeDialog += " Vous pouvez éventuellement ajouter un commentaire.</p>";
            deeDialog += "<textarea id='prompt_comment'></textarea>";
            var deeAction = 'create';
            Prompt.render($jddId, $exportFileId, deeDialogTitle, deeDialog, deeAction);
        });
    } else if ($.inArray( 'Relancer', $actions ) != -1 && $submissionStep == 'VALIDATE') {
        var $launchAgainLink = $("<td><a title='Regénérer' href=''><img src='/img/refresh_arrow.png'></a></td>");
        row.append($launchAgainLink);
        $launchAgainLink.click( function(e) {
            e.preventDefault();
            var deeDialogTitle = "Génération d'une DEE";
            var deeDialog = "<p>Vous allez regénérer une DEE. Une notification va être envoyée à la plateforme nationale,";
            deeDialog += " veuillez décrire les modifications du jeu de données qui amènent à regénérer la DEE.</p>";
            deeDialog += "<textarea id='prompt_comment'></textarea>";
            var deeAction = 'update';
            Prompt.render($jddId, $exportFileId, deeDialogTitle, deeDialog, deeAction);
        });
    } else if ($submissionStep != 'VALIDATE'){
        row.append("<td><img src='/img/refresh_arrow_grey.png'/></td>");
    }

    // Download link if file is available
    if ($status == 'COMPLETED') {
        var $downloadLink = $("<td><a href='/gmlexport/download?id=" + $exportFileId + "'><img title='Télécharger les DEE' src='/img/download.png'></a></td>");
        row.append($downloadLink);
    } else if ($status == 'ABORTED') {
        row.append("<td><img title='Erreur lors de la génération DEE' src='/img/warning_red.png'/></td>");
    } else {
        row.append("<td><img title='Télécharger les DEE' src='/img/download_grey.png'/></td>");
    }

    if ($.inArray( 'Annuler', $actions ) != -1) {
        var $cancelLink = $("<td><a href='' title='Annuler'><img src='/img/delete_x_icon.png'></a></td>");
        row.append($cancelLink);
        $cancelLink.click( function(e) {
            e.preventDefault();
            var deeDialogTitle = "Suppression d'une DEE";
            var deeDialog = "<p>Vous allez supprimer une DEE. Une notification va être envoyée à la plateforme nationale,";
            deeDialog += " veuillez décrire raisons de cette suppression.</p>";
            deeDialog += "<textarea id='prompt_comment'></textarea>";
            var deeAction = 'delete';
            Prompt.render($jddId, $exportFileId, deeDialogTitle, deeDialog, deeAction);
        });
    } else {
        row.append("<td><img title='Annuler' src='/img/delete_x_icon_grey.png'/></td>");
    }

    // Update progress bar if RUNNING
    var $progressBar = $contentDiv.parent().find('div.progress');
    if ($status == 'RUNNING' || $status == 'PENDING') {
        if ($progressBar.hasClass('hidden')) {
            $progressBar.removeClass('hidden');
        }
        var $label = 'Génération DEE ' + (($status == 'RUNNING') ? 'en cours...' : 'en attente...');
        setLabel('deeprogress' + $jddId, $label);
        setProgress('deeprogress' + $jddId, $progress);
    }
    // If not RUNNING remove progress bar
    else {
        $progressBar.addClass('hidden');
    }

    $contentDiv.append(table);
}

/**
 * Return list of actions available by status
 *
 * @param $status
 * @returns {Array}
 */
function getActions($status) {
    var $actions = [];
    switch ($status) {
        case 'NOT FOUND':
            $actions = ['Lancer'];
            break;
        case 'PENDING':
        case 'RUNNING':
            $actions = ['Annuler'];
            break;
        case 'COMPLETED':
        case 'ERROR':
        case 'ABORTED':
            $actions = ['Relancer', 'Annuler'];
            break;
        default:
            $actions = ['Lancer', 'Annuler'];
            break;
    }
    return $actions;
}

/**
 * Ajax request to add an export job (and launch jobs if not already running)
 *
 * @param $jddId
 * @param $exportFileId
 * @param $deeAction
 * @parma $comment
 */
function addExportJob($jddId, $exportFileId, $deeAction, $comment) {
    $.getJSON( "/gmlexport/add-job", {
        exportFileId: $exportFileId,
        jddId: $jddId,
        deeAction: $deeAction,
        comment: $comment
    },function( data ) {
        if (data.success) {
            updateStatusAndContent($jddId, $exportFileId, data.status);
            window.location.reload(true);
        }
    });
}

/**
 * Ajax request to cancel a job and delete export file.
 * By SQL cascade it is also removed from jdd table.
 *
 * @param $jddId
 * @param $exportFileId
 * @param $comment
 */
function cancelExport($jddId, $exportFileId, $comment) {
    $.getJSON( "/gmlexport/cancel-export", {
        jddId: $jddId,
        id: $exportFileId,
        comment: $comment
    },function( data ) {
         if (data.success) {
            updateStatusAndContent($jddId, $exportFileId, data.status);
            window.location.reload(true);
        }
    });
}

jQuery(document).ready(function() {


    $('.dee-content').each(function() {
        var $exportFileId = $(this).attr('data-export-file-id');
        var $jddId = $(this).attr('data-jdd-id');
        updateStatusAndContent($jddId, $exportFileId);
    });

    // Periodically update progress for running and pending jobs
    var timerId = setInterval(updateAllPendingAndRunningTasks , 1000);

});

</script>

