<?php
namespace Ign\Bundle\GincoBundle\Repository\Metadata;

use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Ign\Bundle\GincoBundle\Entity\Metadata\FileField;

/**
 * FileFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileFieldRepository extends \Doctrine\ORM\EntityRepository {

	/**
	 * Get the list of requested fields for the file.
	 *
	 * @param String $fileFormat
	 *        	the file format
	 * @return Array[FileField]
	 */
	public function getFileFields($fileFormat) {
		$rsm = new ResultSetMappingBuilder($this->_em);
		$rsm->addRootEntityFromClassMetadata($this->_entityName, 'ff');
		
		// Get the fields specified by the format
		$sql = "SELECT file_field.data, file_field.format, type, is_mandatory, mask, label_csv";
		$sql .= " FROM file_field ";
		$sql .= " LEFT JOIN field on (file_field.data = field.data AND file_field.format = field.format) ";
		$sql .= " WHERE file_field.format = :fileFormat ";
		$sql .= " ORDER BY label_csv ASC";
		
		$query = $this->_em->createNativeQuery($sql, $rsm);
		$query->setParameters([
			'fileFormat' => $fileFormat
		]);
		
		return $query->getResult();
	}
}
