<?php
namespace Ign\Bundle\GincoBundle\Repository\Metadata;

use Doctrine\ORM\Query\ResultSetMappingBuilder;

use Ign\Bundle\GincoBundle\Entity\Metadata\TableFormat;

/**
 * TableFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableFormatRepository extends \Doctrine\ORM\EntityRepository {

	/**
	 * Get the information about a table format.
	 *
	 * @param String $schema
	 *        	the schema identifier
	 * @param String $format
	 *        	the format
	 * @param String $lang
	 *        	the lang
	 * @return Application_Object_Metadata_TableFormat
	 */
	public function getTableFormat($schema, $format, $lang) {
		$rsm = new ResultSetMappingBuilder($this->_em);
		$rsm->addRootEntityFromClassMetadata($this->_entityName, 't');
		
		// Get the fields specified by the format
		$sql = "SELECT format, schema_code, table_name, COALESCE(t.label, tf.label) as label, primary_key ";
		$sql .= " FROM table_format tf";
		$sql .= " LEFT JOIN translation t ON (lang = ? AND table_format = 'TABLE_FORMAT' AND row_pk = format)";
		$sql .= " WHERE schema_code = ? ";
		$sql .= " AND format = ? ";
		
		$query = $this->_em->createNativeQuery($sql, $rsm);
		$query->setParameters(array(
			$lang,
			$schema,
			$format
		));
		
		return $query->getResult()[0];
	}
	
	/**
	 * Get all table formats.
	 *
	 * @return Array[TableFormat]
	 */
	public function getAllTableFormats() {
		$rsm = new ResultSetMappingBuilder($this->_em);
		$rsm->addRootEntityFromClassMetadata($this->_entityName, 't');
	
		$sql = "SELECT format, table_name, schema_code, primary_key, label, definition ";
		$sql .= " FROM metadata.table_format;";
		
		$query = $this->_em->createNativeQuery($sql, $rsm);
		
		return $query->getResult();
	}
	
	
	/**
	 * Trouve toutes les tables qui ne sont ni enfant de la table en entrée, ni la table elle-meme.
	 * @param TableFormat $tableFormat
	 * @return TableFormat[]
	 */
	public function findNotChildTables(TableFormat $tableFormat) {
		
		$sql = "WITH RECURSIVE child_table AS (
					SELECT tf.* 
					FROM metadata.table_format tf 
					JOIN metadata.table_tree tt ON tt.child_table = tf.format
					WHERE tt.parent_table = :parentTable
					UNION
					SELECT tf.* 
					FROM metadata.table_format tf 
					JOIN metadata.table_tree tt ON tt.child_table = tf.format
					JOIN child_table ct ON tt.parent_table = ct.format
				)
				SELECT tf.* FROM metadata.table_format tf 
				LEFT JOIN child_table ct ON ct.format = tf.format
				WHERE ct.format IS NULL
				AND tf.format IS DISTINCT FROM :parentTable" ;
		
		$rsm = new ResultSetMappingBuilder($this->getEntityManager()) ;
		$rsm->addRootEntityFromClassMetadata($this->getClassName(), 'tf') ;
		$query = $this->getEntityManager()->createNativeQuery($sql, $rsm) ;
		$query->setParameter('parentTable', $tableFormat->getFormat()) ;
		
		return $query->getResult() ;
	}
}
