<?php
namespace Ign\Bundle\GincoBundle\Repository\Metadata;

/**
 * TableSchemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableSchemaRepository extends \Doctrine\ORM\EntityRepository {

	public function findAll() {
		return $this->getEntityManager()
			->createQuery('SELECT s FROM IgnGincoBundle:Metadata\TableSchema s INDEX BY s.code ORDER BY s.code ASC')
			->getResult();
	}
}
