imports:
    - { resource: ../config_dev.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/test_ogam/routing_test_ogam.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    test: ~
    session:
        storage_id: session.storage.mock_file


# Doctrine Configuration
doctrine:
    dbal:
        dbname:   "ginco_symfony_ut"

parameters:
    database_name: ginco_symfony_ut

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

twig:
    cache:  false
    
monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
            channels: ["!doctrine"]
        doctrine:
            type: stream
            path:  "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
            channels: doctrine
#        console:
#            type:   console
#            bubble: false
#            verbosity_levels:
#                VERBOSITY_VERBOSE: INFO
#                VERBOSITY_VERY_VERBOSE: DEBUG
#            channels: ["!doctrine"]
        