UPDATE metadata.file_field SET "position"= 1 WHERE format='file_observation' AND data='OGAM_ID_table_observation';
UPDATE metadata.file_field SET "position"= 2 WHERE format='file_observation' AND data='altitudemax';
UPDATE metadata.file_field SET "position"= 3 WHERE format='file_observation' AND data='altitudemin';
UPDATE metadata.file_field SET "position"= 4 WHERE format='file_observation' AND data='altitudemoyenne';
UPDATE metadata.file_field SET "position"= 5 WHERE format='file_observation' AND data='anneerefcommune';
UPDATE metadata.file_field SET "position"= 6 WHERE format='file_observation' AND data='anneerefdepartement';
UPDATE metadata.file_field SET "position"= 7 WHERE format='file_observation' AND data='cdnom';
UPDATE metadata.file_field SET "position"= 8 WHERE format='file_observation' AND data='cdref';
UPDATE metadata.file_field SET "position"= 9 WHERE format='file_observation' AND data='codecommune';
UPDATE metadata.file_field SET "position"= 10 WHERE format='file_observation' AND data='codedepartement';
UPDATE metadata.file_field SET "position"= 11 WHERE format='file_observation' AND data='codeen';
UPDATE metadata.file_field SET "position"= 12 WHERE format='file_observation' AND data='codehabitat';
UPDATE metadata.file_field SET "position"= 13 WHERE format='file_observation' AND data='codehabref';
UPDATE metadata.file_field SET "position"= 14 WHERE format='file_observation' AND data='codeidcnpdispositif';
UPDATE metadata.file_field SET "position"= 15 WHERE format='file_observation' AND data='codemaille';
UPDATE metadata.file_field SET "position"= 16 WHERE format='file_observation' AND data='codeme';
UPDATE metadata.file_field SET "position"= 17 WHERE format='file_observation' AND data='commentaire';
UPDATE metadata.file_field SET "position"= 18 WHERE format='file_observation' AND data='datedetermination';
UPDATE metadata.file_field SET "position"= 19 WHERE format='file_observation' AND data='dateme';
UPDATE metadata.file_field SET "position"= 20 WHERE format='file_observation' AND data='deefloutage';
UPDATE metadata.file_field SET "position"= 21 WHERE format='file_observation' AND data='denombrementmax';
UPDATE metadata.file_field SET "position"= 22 WHERE format='file_observation' AND data='denombrementmin';
UPDATE metadata.file_field SET "position"= 23 WHERE format='file_observation' AND data='determinateuridentite';
UPDATE metadata.file_field SET "position"= 24 WHERE format='file_observation' AND data='determinateurmail';
UPDATE metadata.file_field SET "position"= 25 WHERE format='file_observation' AND data='determinateurnomorganisme';
UPDATE metadata.file_field SET "position"= 26 WHERE format='file_observation' AND data='diffusionniveauprecision';
UPDATE metadata.file_field SET "position"= 27 WHERE format='file_observation' AND data='dspublique';
UPDATE metadata.file_field SET "position"= 28 WHERE format='file_observation' AND data='geometrie';
UPDATE metadata.file_field SET "position"= 29 WHERE format='file_observation' AND data='heuredatedebut';
UPDATE metadata.file_field SET "position"= 30 WHERE format='file_observation' AND data='heuredatefin';
UPDATE metadata.file_field SET "position"= 31 WHERE format='file_observation' AND data='identifiantorigine';
UPDATE metadata.file_field SET "position"= 32 WHERE format='file_observation' AND data='identifiantpermanent';
UPDATE metadata.file_field SET "position"= 33 WHERE format='file_observation' AND data='identifiantregroupementpermanent';
UPDATE metadata.file_field SET "position"= 34 WHERE format='file_observation' AND data='jddcode';
UPDATE metadata.file_field SET "position"= 35 WHERE format='file_observation' AND data='jddid';
UPDATE metadata.file_field SET "position"= 36 WHERE format='file_observation' AND data='jddmetadonneedeeid';
UPDATE metadata.file_field SET "position"= 37 WHERE format='file_observation' AND data='jddsourceid';
UPDATE metadata.file_field SET "position"= 38 WHERE format='file_observation' AND data='jourdatedebut';
UPDATE metadata.file_field SET "position"= 39 WHERE format='file_observation' AND data='jourdatefin';
UPDATE metadata.file_field SET "position"= 40 WHERE format='file_observation' AND data='methoderegroupement';
UPDATE metadata.file_field SET "position"= 41 WHERE format='file_observation' AND data='natureobjetgeo';
UPDATE metadata.file_field SET "position"= 42 WHERE format='file_observation' AND data='nomcite';
UPDATE metadata.file_field SET "position"= 43 WHERE format='file_observation' AND data='nomcommune';
UPDATE metadata.file_field SET "position"= 44 WHERE format='file_observation' AND data='nomrefmaille';
UPDATE metadata.file_field SET "position"= 45 WHERE format='file_observation' AND data='nomvalide';
UPDATE metadata.file_field SET "position"= 46 WHERE format='file_observation' AND data='objetdenombrement';
UPDATE metadata.file_field SET "position"= 47 WHERE format='file_observation' AND data='obscontexte';
UPDATE metadata.file_field SET "position"= 48 WHERE format='file_observation' AND data='obsdescription';
UPDATE metadata.file_field SET "position"= 49 WHERE format='file_observation' AND data='observateuridentite';
UPDATE metadata.file_field SET "position"= 50 WHERE format='file_observation' AND data='observateurmail';
UPDATE metadata.file_field SET "position"= 51 WHERE format='file_observation' AND data='observateurnomorganisme';
UPDATE metadata.file_field SET "position"= 52 WHERE format='file_observation' AND data='obsmethode';
UPDATE metadata.file_field SET "position"= 53 WHERE format='file_observation' AND data='occetatbiologique';
UPDATE metadata.file_field SET "position"= 54 WHERE format='file_observation' AND data='occmethodedetermination';
UPDATE metadata.file_field SET "position"= 55 WHERE format='file_observation' AND data='occnaturalite';
UPDATE metadata.file_field SET "position"= 56 WHERE format='file_observation' AND data='occsexe';
UPDATE metadata.file_field SET "position"= 57 WHERE format='file_observation' AND data='occstadedevie';
UPDATE metadata.file_field SET "position"= 58 WHERE format='file_observation' AND data='occstatutbiogeographique';
UPDATE metadata.file_field SET "position"= 59 WHERE format='file_observation' AND data='occstatutbiologique';
UPDATE metadata.file_field SET "position"= 60 WHERE format='file_observation' AND data='organismegestionnairedonnee';
UPDATE metadata.file_field SET "position"= 61 WHERE format='file_observation' AND data='organismestandard';
UPDATE metadata.file_field SET "position"= 62 WHERE format='file_observation' AND data='orgtransformation';
UPDATE metadata.file_field SET "position"= 63 WHERE format='file_observation' AND data='precisiongeometrie';
UPDATE metadata.file_field SET "position"= 64 WHERE format='file_observation' AND data='preuveexistante';
UPDATE metadata.file_field SET "position"= 65 WHERE format='file_observation' AND data='preuvenonnumerique';
UPDATE metadata.file_field SET "position"= 66 WHERE format='file_observation' AND data='preuvenumerique';
UPDATE metadata.file_field SET "position"= 67 WHERE format='file_observation' AND data='profondeurmax';
UPDATE metadata.file_field SET "position"= 68 WHERE format='file_observation' AND data='profondeurmin';
UPDATE metadata.file_field SET "position"= 69 WHERE format='file_observation' AND data='profondeurmoyenne';
UPDATE metadata.file_field SET "position"= 70 WHERE format='file_observation' AND data='referencebiblio';
UPDATE metadata.file_field SET "position"= 71 WHERE format='file_observation' AND data='refhabitat';
UPDATE metadata.file_field SET "position"= 72 WHERE format='file_observation' AND data='statutobservation';
UPDATE metadata.file_field SET "position"= 73 WHERE format='file_observation' AND data='statutsource';
UPDATE metadata.file_field SET "position"= 74 WHERE format='file_observation' AND data='typedenombrement';
UPDATE metadata.file_field SET "position"= 75 WHERE format='file_observation' AND data='typeen';
UPDATE metadata.file_field SET "position"= 76 WHERE format='file_observation' AND data='typeinfogeocommune';
UPDATE metadata.file_field SET "position"= 77 WHERE format='file_observation' AND data='typeinfogeodepartement';
UPDATE metadata.file_field SET "position"= 78 WHERE format='file_observation' AND data='typeinfogeoen';
UPDATE metadata.file_field SET "position"= 79 WHERE format='file_observation' AND data='typeinfogeomaille';
UPDATE metadata.file_field SET "position"= 80 WHERE format='file_observation' AND data='typeinfogeome';
UPDATE metadata.file_field SET "position"= 81 WHERE format='file_observation' AND data='typeregroupement';
UPDATE metadata.file_field SET "position"= 82 WHERE format='file_observation' AND data='validateuridentite';
UPDATE metadata.file_field SET "position"= 83 WHERE format='file_observation' AND data='validateurmail';
UPDATE metadata.file_field SET "position"= 84 WHERE format='file_observation' AND data='validateurnomorganisme';
UPDATE metadata.file_field SET "position"= 85 WHERE format='file_observation' AND data='versionen';
UPDATE metadata.file_field SET "position"= 86 WHERE format='file_observation' AND data='versionme';
UPDATE metadata.file_field SET "position"= 87 WHERE format='file_observation' AND data='versionrefhabitat';
UPDATE metadata.file_field SET "position"= 88 WHERE format='file_observation' AND data='versionrefmaille';
UPDATE metadata.file_field SET "position"= 89 WHERE format='file_observation' AND data='versiontaxref';


UPDATE metadata_work.file_field SET "position"= 1 WHERE format='file_observation' AND data='OGAM_ID_table_observation';
UPDATE metadata_work.file_field SET "position"= 2 WHERE format='file_observation' AND data='altitudemax';
UPDATE metadata_work.file_field SET "position"= 3 WHERE format='file_observation' AND data='altitudemin';
UPDATE metadata_work.file_field SET "position"= 4 WHERE format='file_observation' AND data='altitudemoyenne';
UPDATE metadata_work.file_field SET "position"= 5 WHERE format='file_observation' AND data='anneerefcommune';
UPDATE metadata_work.file_field SET "position"= 6 WHERE format='file_observation' AND data='anneerefdepartement';
UPDATE metadata_work.file_field SET "position"= 7 WHERE format='file_observation' AND data='cdnom';
UPDATE metadata_work.file_field SET "position"= 8 WHERE format='file_observation' AND data='cdref';
UPDATE metadata_work.file_field SET "position"= 9 WHERE format='file_observation' AND data='codecommune';
UPDATE metadata_work.file_field SET "position"= 10 WHERE format='file_observation' AND data='codedepartement';
UPDATE metadata_work.file_field SET "position"= 11 WHERE format='file_observation' AND data='codeen';
UPDATE metadata_work.file_field SET "position"= 12 WHERE format='file_observation' AND data='codehabitat';
UPDATE metadata_work.file_field SET "position"= 13 WHERE format='file_observation' AND data='codehabref';
UPDATE metadata_work.file_field SET "position"= 14 WHERE format='file_observation' AND data='codeidcnpdispositif';
UPDATE metadata_work.file_field SET "position"= 15 WHERE format='file_observation' AND data='codemaille';
UPDATE metadata_work.file_field SET "position"= 16 WHERE format='file_observation' AND data='codeme';
UPDATE metadata_work.file_field SET "position"= 17 WHERE format='file_observation' AND data='commentaire';
UPDATE metadata_work.file_field SET "position"= 18 WHERE format='file_observation' AND data='datedetermination';
UPDATE metadata_work.file_field SET "position"= 19 WHERE format='file_observation' AND data='dateme';
UPDATE metadata_work.file_field SET "position"= 20 WHERE format='file_observation' AND data='deefloutage';
UPDATE metadata_work.file_field SET "position"= 21 WHERE format='file_observation' AND data='denombrementmax';
UPDATE metadata_work.file_field SET "position"= 22 WHERE format='file_observation' AND data='denombrementmin';
UPDATE metadata_work.file_field SET "position"= 23 WHERE format='file_observation' AND data='determinateuridentite';
UPDATE metadata_work.file_field SET "position"= 24 WHERE format='file_observation' AND data='determinateurmail';
UPDATE metadata_work.file_field SET "position"= 25 WHERE format='file_observation' AND data='determinateurnomorganisme';
UPDATE metadata_work.file_field SET "position"= 26 WHERE format='file_observation' AND data='diffusionniveauprecision';
UPDATE metadata_work.file_field SET "position"= 27 WHERE format='file_observation' AND data='dspublique';
UPDATE metadata_work.file_field SET "position"= 28 WHERE format='file_observation' AND data='geometrie';
UPDATE metadata_work.file_field SET "position"= 29 WHERE format='file_observation' AND data='heuredatedebut';
UPDATE metadata_work.file_field SET "position"= 30 WHERE format='file_observation' AND data='heuredatefin';
UPDATE metadata_work.file_field SET "position"= 31 WHERE format='file_observation' AND data='identifiantorigine';
UPDATE metadata_work.file_field SET "position"= 32 WHERE format='file_observation' AND data='identifiantpermanent';
UPDATE metadata_work.file_field SET "position"= 33 WHERE format='file_observation' AND data='identifiantregroupementpermanent';
UPDATE metadata_work.file_field SET "position"= 34 WHERE format='file_observation' AND data='jddcode';
UPDATE metadata_work.file_field SET "position"= 35 WHERE format='file_observation' AND data='jddid';
UPDATE metadata_work.file_field SET "position"= 36 WHERE format='file_observation' AND data='jddmetadonneedeeid';
UPDATE metadata_work.file_field SET "position"= 37 WHERE format='file_observation' AND data='jddsourceid';
UPDATE metadata_work.file_field SET "position"= 38 WHERE format='file_observation' AND data='jourdatedebut';
UPDATE metadata_work.file_field SET "position"= 39 WHERE format='file_observation' AND data='jourdatefin';
UPDATE metadata_work.file_field SET "position"= 40 WHERE format='file_observation' AND data='methoderegroupement';
UPDATE metadata_work.file_field SET "position"= 41 WHERE format='file_observation' AND data='natureobjetgeo';
UPDATE metadata_work.file_field SET "position"= 42 WHERE format='file_observation' AND data='nomcite';
UPDATE metadata_work.file_field SET "position"= 43 WHERE format='file_observation' AND data='nomcommune';
UPDATE metadata_work.file_field SET "position"= 44 WHERE format='file_observation' AND data='nomrefmaille';
UPDATE metadata_work.file_field SET "position"= 45 WHERE format='file_observation' AND data='nomvalide';
UPDATE metadata_work.file_field SET "position"= 46 WHERE format='file_observation' AND data='objetdenombrement';
UPDATE metadata_work.file_field SET "position"= 47 WHERE format='file_observation' AND data='obscontexte';
UPDATE metadata_work.file_field SET "position"= 48 WHERE format='file_observation' AND data='obsdescription';
UPDATE metadata_work.file_field SET "position"= 49 WHERE format='file_observation' AND data='observateuridentite';
UPDATE metadata_work.file_field SET "position"= 50 WHERE format='file_observation' AND data='observateurmail';
UPDATE metadata_work.file_field SET "position"= 51 WHERE format='file_observation' AND data='observateurnomorganisme';
UPDATE metadata_work.file_field SET "position"= 52 WHERE format='file_observation' AND data='obsmethode';
UPDATE metadata_work.file_field SET "position"= 53 WHERE format='file_observation' AND data='occetatbiologique';
UPDATE metadata_work.file_field SET "position"= 54 WHERE format='file_observation' AND data='occmethodedetermination';
UPDATE metadata_work.file_field SET "position"= 55 WHERE format='file_observation' AND data='occnaturalite';
UPDATE metadata_work.file_field SET "position"= 56 WHERE format='file_observation' AND data='occsexe';
UPDATE metadata_work.file_field SET "position"= 57 WHERE format='file_observation' AND data='occstadedevie';
UPDATE metadata_work.file_field SET "position"= 58 WHERE format='file_observation' AND data='occstatutbiogeographique';
UPDATE metadata_work.file_field SET "position"= 59 WHERE format='file_observation' AND data='occstatutbiologique';
UPDATE metadata_work.file_field SET "position"= 60 WHERE format='file_observation' AND data='organismegestionnairedonnee';
UPDATE metadata_work.file_field SET "position"= 61 WHERE format='file_observation' AND data='organismestandard';
UPDATE metadata_work.file_field SET "position"= 62 WHERE format='file_observation' AND data='orgtransformation';
UPDATE metadata_work.file_field SET "position"= 63 WHERE format='file_observation' AND data='precisiongeometrie';
UPDATE metadata_work.file_field SET "position"= 64 WHERE format='file_observation' AND data='preuveexistante';
UPDATE metadata_work.file_field SET "position"= 65 WHERE format='file_observation' AND data='preuvenonnumerique';
UPDATE metadata_work.file_field SET "position"= 66 WHERE format='file_observation' AND data='preuvenumerique';
UPDATE metadata_work.file_field SET "position"= 67 WHERE format='file_observation' AND data='profondeurmax';
UPDATE metadata_work.file_field SET "position"= 68 WHERE format='file_observation' AND data='profondeurmin';
UPDATE metadata_work.file_field SET "position"= 69 WHERE format='file_observation' AND data='profondeurmoyenne';
UPDATE metadata_work.file_field SET "position"= 70 WHERE format='file_observation' AND data='referencebiblio';
UPDATE metadata_work.file_field SET "position"= 71 WHERE format='file_observation' AND data='refhabitat';
UPDATE metadata_work.file_field SET "position"= 72 WHERE format='file_observation' AND data='statutobservation';
UPDATE metadata_work.file_field SET "position"= 73 WHERE format='file_observation' AND data='statutsource';
UPDATE metadata_work.file_field SET "position"= 74 WHERE format='file_observation' AND data='typedenombrement';
UPDATE metadata_work.file_field SET "position"= 75 WHERE format='file_observation' AND data='typeen';
UPDATE metadata_work.file_field SET "position"= 76 WHERE format='file_observation' AND data='typeinfogeocommune';
UPDATE metadata_work.file_field SET "position"= 77 WHERE format='file_observation' AND data='typeinfogeodepartement';
UPDATE metadata_work.file_field SET "position"= 78 WHERE format='file_observation' AND data='typeinfogeoen';
UPDATE metadata_work.file_field SET "position"= 79 WHERE format='file_observation' AND data='typeinfogeomaille';
UPDATE metadata_work.file_field SET "position"= 80 WHERE format='file_observation' AND data='typeinfogeome';
UPDATE metadata_work.file_field SET "position"= 81 WHERE format='file_observation' AND data='typeregroupement';
UPDATE metadata_work.file_field SET "position"= 82 WHERE format='file_observation' AND data='validateuridentite';
UPDATE metadata_work.file_field SET "position"= 83 WHERE format='file_observation' AND data='validateurmail';
UPDATE metadata_work.file_field SET "position"= 84 WHERE format='file_observation' AND data='validateurnomorganisme';
UPDATE metadata_work.file_field SET "position"= 85 WHERE format='file_observation' AND data='versionen';
UPDATE metadata_work.file_field SET "position"= 86 WHERE format='file_observation' AND data='versionme';
UPDATE metadata_work.file_field SET "position"= 87 WHERE format='file_observation' AND data='versionrefhabitat';
UPDATE metadata_work.file_field SET "position"= 88 WHERE format='file_observation' AND data='versionrefmaille';
UPDATE metadata_work.file_field SET "position"= 89 WHERE format='file_observation' AND data='versiontaxref';


UPDATE metadata.table_field SET position='1' WHERE data='SUBMISSION_ID' AND format='table_observation';
UPDATE metadata.table_field SET position='2' WHERE data='PROVIDER_ID' AND format='table_observation';
UPDATE metadata.table_field SET position='3' WHERE data='OGAM_ID_table_observation' AND format='table_observation';
UPDATE metadata.table_field SET position='4' WHERE data='codecommune' AND format='table_observation';
UPDATE metadata.table_field SET position='5' WHERE data='nomcommune' AND format='table_observation';
UPDATE metadata.table_field SET position='6' WHERE data='anneerefcommune' AND format='table_observation';
UPDATE metadata.table_field SET position='7' WHERE data='typeinfogeocommune' AND format='table_observation';
UPDATE metadata.table_field SET position='8' WHERE data='denombrementmin' AND format='table_observation';
UPDATE metadata.table_field SET position='9' WHERE data='denombrementmax' AND format='table_observation';
UPDATE metadata.table_field SET position='10' WHERE data='objetdenombrement' AND format='table_observation';
UPDATE metadata.table_field SET position='11' WHERE data='typedenombrement' AND format='table_observation';
UPDATE metadata.table_field SET position='12' WHERE data='codedepartement' AND format='table_observation';
UPDATE metadata.table_field SET position='13' WHERE data='anneerefdepartement' AND format='table_observation';
UPDATE metadata.table_field SET position='14' WHERE data='typeinfogeodepartement' AND format='table_observation';
UPDATE metadata.table_field SET position='15' WHERE data='typeen' AND format='table_observation';
UPDATE metadata.table_field SET position='16' WHERE data='codeen' AND format='table_observation';
UPDATE metadata.table_field SET position='17' WHERE data='versionen' AND format='table_observation';
UPDATE metadata.table_field SET position='18' WHERE data='typeinfogeoen' AND format='table_observation';
UPDATE metadata.table_field SET position='19' WHERE data='refhabitat' AND format='table_observation';
UPDATE metadata.table_field SET position='20' WHERE data='codehabitat' AND format='table_observation';
UPDATE metadata.table_field SET position='21' WHERE data='versionrefhabitat' AND format='table_observation';
UPDATE metadata.table_field SET position='22' WHERE data='codehabref' AND format='table_observation';
UPDATE metadata.table_field SET position='23' WHERE data='codemaille' AND format='table_observation';
UPDATE metadata.table_field SET position='24' WHERE data='versionrefmaille' AND format='table_observation';
UPDATE metadata.table_field SET position='25' WHERE data='nomrefmaille' AND format='table_observation';
UPDATE metadata.table_field SET position='26' WHERE data='typeinfogeomaille' AND format='table_observation';
UPDATE metadata.table_field SET position='27' WHERE data='codeme' AND format='table_observation';
UPDATE metadata.table_field SET position='28' WHERE data='versionme' AND format='table_observation';
UPDATE metadata.table_field SET position='29' WHERE data='dateme' AND format='table_observation';
UPDATE metadata.table_field SET position='30' WHERE data='typeinfogeome' AND format='table_observation';
UPDATE metadata.table_field SET position='31' WHERE data='observateurnomorganisme' AND format='table_observation';
UPDATE metadata.table_field SET position='32' WHERE data='observateuridentite' AND format='table_observation';
UPDATE metadata.table_field SET position='33' WHERE data='observateurmail' AND format='table_observation';
UPDATE metadata.table_field SET position='34' WHERE data='determinateurnomorganisme' AND format='table_observation';
UPDATE metadata.table_field SET position='35' WHERE data='determinateuridentite' AND format='table_observation';
UPDATE metadata.table_field SET position='36' WHERE data='determinateurmail' AND format='table_observation';
UPDATE metadata.table_field SET position='37' WHERE data='validateurnomorganisme' AND format='table_observation';
UPDATE metadata.table_field SET position='38' WHERE data='validateuridentite' AND format='table_observation';
UPDATE metadata.table_field SET position='39' WHERE data='validateurmail' AND format='table_observation';
UPDATE metadata.table_field SET position='40' WHERE data='identifiantorigine' AND format='table_observation';
UPDATE metadata.table_field SET position='41' WHERE data='dspublique' AND format='table_observation';
UPDATE metadata.table_field SET position='42' WHERE data='diffusionniveauprecision' AND format='table_observation';
UPDATE metadata.table_field SET position='43' WHERE data='deefloutage' AND format='table_observation';
UPDATE metadata.table_field SET position='44' WHERE data='sensible' AND format='table_observation';
UPDATE metadata.table_field SET position='45' WHERE data='sensiniveau' AND format='table_observation';
UPDATE metadata.table_field SET position='46' WHERE data='sensidateattribution' AND format='table_observation';
UPDATE metadata.table_field SET position='47' WHERE data='sensireferentiel' AND format='table_observation';
UPDATE metadata.table_field SET position='48' WHERE data='sensiversionreferentiel' AND format='table_observation';
UPDATE metadata.table_field SET position='49' WHERE data='statutsource' AND format='table_observation';
UPDATE metadata.table_field SET position='50' WHERE data='jddcode' AND format='table_observation';
UPDATE metadata.table_field SET position='51' WHERE data='jddid' AND format='table_observation';
UPDATE metadata.table_field SET position='52' WHERE data='jddsourceid' AND format='table_observation';
UPDATE metadata.table_field SET position='53' WHERE data='jddmetadonneedeeid' AND format='table_observation';
UPDATE metadata.table_field SET position='54' WHERE data='organismegestionnairedonnee' AND format='table_observation';
UPDATE metadata.table_field SET position='55' WHERE data='codeidcnpdispositif' AND format='table_observation';
UPDATE metadata.table_field SET position='56' WHERE data='deedatedernieremodification' AND format='table_observation';
UPDATE metadata.table_field SET position='57' WHERE data='referencebiblio' AND format='table_observation';
UPDATE metadata.table_field SET position='58' WHERE data='orgtransformation' AND format='table_observation';
UPDATE metadata.table_field SET position='59' WHERE data='identifiantpermanent' AND format='table_observation';
UPDATE metadata.table_field SET position='60' WHERE data='statutobservation' AND format='table_observation';
UPDATE metadata.table_field SET position='61' WHERE data='nomcite' AND format='table_observation';
UPDATE metadata.table_field SET position='62' WHERE data='jourdatedebut' AND format='table_observation';
UPDATE metadata.table_field SET position='63' WHERE data='jourdatefin' AND format='table_observation';
UPDATE metadata.table_field SET position='64' WHERE data='altitudemin' AND format='table_observation';
UPDATE metadata.table_field SET position='65' WHERE data='altitudemax' AND format='table_observation';
UPDATE metadata.table_field SET position='66' WHERE data='profondeurmin' AND format='table_observation';
UPDATE metadata.table_field SET position='67' WHERE data='profondeurmax' AND format='table_observation';
UPDATE metadata.table_field SET position='68' WHERE data='cdnom' AND format='table_observation';
UPDATE metadata.table_field SET position='69' WHERE data='cdref' AND format='table_observation';
UPDATE metadata.table_field SET position='70' WHERE data='versiontaxref' AND format='table_observation';
UPDATE metadata.table_field SET position='71' WHERE data='datedetermination' AND format='table_observation';
UPDATE metadata.table_field SET position='72' WHERE data='organismestandard' AND format='table_observation';
UPDATE metadata.table_field SET position='73' WHERE data='commentaire' AND format='table_observation';
UPDATE metadata.table_field SET position='74' WHERE data='obsdescription' AND format='table_observation';
UPDATE metadata.table_field SET position='75' WHERE data='obsmethode' AND format='table_observation';
UPDATE metadata.table_field SET position='76' WHERE data='occetatbiologique' AND format='table_observation';
UPDATE metadata.table_field SET position='77' WHERE data='occstatutbiogeographique' AND format='table_observation';
UPDATE metadata.table_field SET position='78' WHERE data='occmethodedetermination' AND format='table_observation';
UPDATE metadata.table_field SET position='79' WHERE data='occnaturalite' AND format='table_observation';
UPDATE metadata.table_field SET position='80' WHERE data='occsexe' AND format='table_observation';
UPDATE metadata.table_field SET position='81' WHERE data='occstadedevie' AND format='table_observation';
UPDATE metadata.table_field SET position='82' WHERE data='occstatutbiologique' AND format='table_observation';
UPDATE metadata.table_field SET position='83' WHERE data='preuveexistante' AND format='table_observation';
UPDATE metadata.table_field SET position='84' WHERE data='preuvenonnumerique' AND format='table_observation';
UPDATE metadata.table_field SET position='85' WHERE data='preuvenumerique' AND format='table_observation';
UPDATE metadata.table_field SET position='86' WHERE data='obscontexte' AND format='table_observation';
UPDATE metadata.table_field SET position='87' WHERE data='identifiantregroupementpermanent' AND format='table_observation';
UPDATE metadata.table_field SET position='88' WHERE data='methoderegroupement' AND format='table_observation';
UPDATE metadata.table_field SET position='89' WHERE data='typeregroupement' AND format='table_observation';
UPDATE metadata.table_field SET position='90' WHERE data='altitudemoyenne' AND format='table_observation';
UPDATE metadata.table_field SET position='91' WHERE data='profondeurmoyenne' AND format='table_observation';
UPDATE metadata.table_field SET position='92' WHERE data='geometrie' AND format='table_observation';
UPDATE metadata.table_field SET position='93' WHERE data='natureobjetgeo' AND format='table_observation';
UPDATE metadata.table_field SET position='94' WHERE data='precisiongeometrie' AND format='table_observation';
UPDATE metadata.table_field SET position='95' WHERE data='sensimanuelle' AND format='table_observation';
UPDATE metadata.table_field SET position='96' WHERE data='sensialerte' AND format='table_observation';
UPDATE metadata.table_field SET position='97' WHERE data='codemaillecalcule' AND format='table_observation';
UPDATE metadata.table_field SET position='98' WHERE data='codecommunecalcule' AND format='table_observation';
UPDATE metadata.table_field SET position='99' WHERE data='nomcommunecalcule' AND format='table_observation';
UPDATE metadata.table_field SET position='100' WHERE data='codedepartementcalcule' AND format='table_observation';
UPDATE metadata.table_field SET position='101' WHERE data='heuredatedebut' AND format='table_observation';
UPDATE metadata.table_field SET position='102' WHERE data='heuredatefin' AND format='table_observation';
UPDATE metadata.table_field SET position='103' WHERE data='nomvalide' AND format='table_observation';



UPDATE metadata_work.table_field SET position=1 WHERE data='SUBMISSION_ID' AND format='table_observation';
UPDATE metadata_work.table_field SET position=2 WHERE data='PROVIDER_ID' AND format='table_observation';
UPDATE metadata_work.table_field SET position=3 WHERE data='OGAM_ID_table_observation' AND format='table_observation';
UPDATE metadata_work.table_field SET position=4 WHERE data='codecommune' AND format='table_observation';
UPDATE metadata_work.table_field SET position=5 WHERE data='nomcommune' AND format='table_observation';
UPDATE metadata_work.table_field SET position=6 WHERE data='anneerefcommune' AND format='table_observation';
UPDATE metadata_work.table_field SET position=7 WHERE data='typeinfogeocommune' AND format='table_observation';
UPDATE metadata_work.table_field SET position=8 WHERE data='denombrementmin' AND format='table_observation';
UPDATE metadata_work.table_field SET position=9 WHERE data='denombrementmax' AND format='table_observation';
UPDATE metadata_work.table_field SET position=10 WHERE data='objetdenombrement' AND format='table_observation';
UPDATE metadata_work.table_field SET position=11 WHERE data='typedenombrement' AND format='table_observation';
UPDATE metadata_work.table_field SET position=12 WHERE data='codedepartement' AND format='table_observation';
UPDATE metadata_work.table_field SET position=13 WHERE data='anneerefdepartement' AND format='table_observation';
UPDATE metadata_work.table_field SET position=14 WHERE data='typeinfogeodepartement' AND format='table_observation';
UPDATE metadata_work.table_field SET position=15 WHERE data='typeen' AND format='table_observation';
UPDATE metadata_work.table_field SET position=16 WHERE data='codeen' AND format='table_observation';
UPDATE metadata_work.table_field SET position=17 WHERE data='versionen' AND format='table_observation';
UPDATE metadata_work.table_field SET position=18 WHERE data='typeinfogeoen' AND format='table_observation';
UPDATE metadata_work.table_field SET position=19 WHERE data='refhabitat' AND format='table_observation';
UPDATE metadata_work.table_field SET position=20 WHERE data='codehabitat' AND format='table_observation';
UPDATE metadata_work.table_field SET position=21 WHERE data='versionrefhabitat' AND format='table_observation';
UPDATE metadata_work.table_field SET position=22 WHERE data='codehabref' AND format='table_observation';
UPDATE metadata_work.table_field SET position=23 WHERE data='codemaille' AND format='table_observation';
UPDATE metadata_work.table_field SET position=24 WHERE data='versionrefmaille' AND format='table_observation';
UPDATE metadata_work.table_field SET position=25 WHERE data='nomrefmaille' AND format='table_observation';
UPDATE metadata_work.table_field SET position=26 WHERE data='typeinfogeomaille' AND format='table_observation';
UPDATE metadata_work.table_field SET position=27 WHERE data='codeme' AND format='table_observation';
UPDATE metadata_work.table_field SET position=28 WHERE data='versionme' AND format='table_observation';
UPDATE metadata_work.table_field SET position=29 WHERE data='dateme' AND format='table_observation';
UPDATE metadata_work.table_field SET position=30 WHERE data='typeinfogeome' AND format='table_observation';
UPDATE metadata_work.table_field SET position=31 WHERE data='observateurnomorganisme' AND format='table_observation';
UPDATE metadata_work.table_field SET position=32 WHERE data='observateuridentite' AND format='table_observation';
UPDATE metadata_work.table_field SET position=33 WHERE data='observateurmail' AND format='table_observation';
UPDATE metadata_work.table_field SET position=34 WHERE data='determinateurnomorganisme' AND format='table_observation';
UPDATE metadata_work.table_field SET position=35 WHERE data='determinateuridentite' AND format='table_observation';
UPDATE metadata_work.table_field SET position=36 WHERE data='determinateurmail' AND format='table_observation';
UPDATE metadata_work.table_field SET position=37 WHERE data='validateurnomorganisme' AND format='table_observation';
UPDATE metadata_work.table_field SET position=38 WHERE data='validateuridentite' AND format='table_observation';
UPDATE metadata_work.table_field SET position=39 WHERE data='validateurmail' AND format='table_observation';
UPDATE metadata_work.table_field SET position=40 WHERE data='identifiantorigine' AND format='table_observation';
UPDATE metadata_work.table_field SET position=41 WHERE data='dspublique' AND format='table_observation';
UPDATE metadata_work.table_field SET position=42 WHERE data='diffusionniveauprecision' AND format='table_observation';
UPDATE metadata_work.table_field SET position=43 WHERE data='deefloutage' AND format='table_observation';
UPDATE metadata_work.table_field SET position=44 WHERE data='sensible' AND format='table_observation';
UPDATE metadata_work.table_field SET position=45 WHERE data='sensiniveau' AND format='table_observation';
UPDATE metadata_work.table_field SET position=46 WHERE data='sensidateattribution' AND format='table_observation';
UPDATE metadata_work.table_field SET position=47 WHERE data='sensireferentiel' AND format='table_observation';
UPDATE metadata_work.table_field SET position=48 WHERE data='sensiversionreferentiel' AND format='table_observation';
UPDATE metadata_work.table_field SET position=49 WHERE data='statutsource' AND format='table_observation';
UPDATE metadata_work.table_field SET position=50 WHERE data='jddcode' AND format='table_observation';
UPDATE metadata_work.table_field SET position=51 WHERE data='jddid' AND format='table_observation';
UPDATE metadata_work.table_field SET position=52 WHERE data='jddsourceid' AND format='table_observation';
UPDATE metadata_work.table_field SET position=53 WHERE data='jddmetadonneedeeid' AND format='table_observation';
UPDATE metadata_work.table_field SET position=54 WHERE data='organismegestionnairedonnee' AND format='table_observation';
UPDATE metadata_work.table_field SET position=55 WHERE data='codeidcnpdispositif' AND format='table_observation';
UPDATE metadata_work.table_field SET position=56 WHERE data='deedatedernieremodification' AND format='table_observation';
UPDATE metadata_work.table_field SET position=57 WHERE data='referencebiblio' AND format='table_observation';
UPDATE metadata_work.table_field SET position=58 WHERE data='orgtransformation' AND format='table_observation';
UPDATE metadata_work.table_field SET position=59 WHERE data='identifiantpermanent' AND format='table_observation';
UPDATE metadata_work.table_field SET position=60 WHERE data='statutobservation' AND format='table_observation';
UPDATE metadata_work.table_field SET position=61 WHERE data='nomcite' AND format='table_observation';
UPDATE metadata_work.table_field SET position=62 WHERE data='jourdatedebut' AND format='table_observation';
UPDATE metadata_work.table_field SET position=63 WHERE data='jourdatefin' AND format='table_observation';
UPDATE metadata_work.table_field SET position=64 WHERE data='altitudemin' AND format='table_observation';
UPDATE metadata_work.table_field SET position=65 WHERE data='altitudemax' AND format='table_observation';
UPDATE metadata_work.table_field SET position=66 WHERE data='profondeurmin' AND format='table_observation';
UPDATE metadata_work.table_field SET position=67 WHERE data='profondeurmax' AND format='table_observation';
UPDATE metadata_work.table_field SET position=68 WHERE data='cdnom' AND format='table_observation';
UPDATE metadata_work.table_field SET position=69 WHERE data='cdref' AND format='table_observation';
UPDATE metadata_work.table_field SET position=70 WHERE data='versiontaxref' AND format='table_observation';
UPDATE metadata_work.table_field SET position=71 WHERE data='datedetermination' AND format='table_observation';
UPDATE metadata_work.table_field SET position=72 WHERE data='organismestandard' AND format='table_observation';
UPDATE metadata_work.table_field SET position=73 WHERE data='commentaire' AND format='table_observation';
UPDATE metadata_work.table_field SET position=74 WHERE data='obsdescription' AND format='table_observation';
UPDATE metadata_work.table_field SET position=75 WHERE data='obsmethode' AND format='table_observation';
UPDATE metadata_work.table_field SET position=76 WHERE data='occetatbiologique' AND format='table_observation';
UPDATE metadata_work.table_field SET position=77 WHERE data='occstatutbiogeographique' AND format='table_observation';
UPDATE metadata_work.table_field SET position=78 WHERE data='occmethodedetermination' AND format='table_observation';
UPDATE metadata_work.table_field SET position=79 WHERE data='occnaturalite' AND format='table_observation';
UPDATE metadata_work.table_field SET position=80 WHERE data='occsexe' AND format='table_observation';
UPDATE metadata_work.table_field SET position=81 WHERE data='occstadedevie' AND format='table_observation';
UPDATE metadata_work.table_field SET position=82 WHERE data='occstatutbiologique' AND format='table_observation';
UPDATE metadata_work.table_field SET position=83 WHERE data='preuveexistante' AND format='table_observation';
UPDATE metadata_work.table_field SET position=84 WHERE data='preuvenonnumerique' AND format='table_observation';
UPDATE metadata_work.table_field SET position=85 WHERE data='preuvenumerique' AND format='table_observation';
UPDATE metadata_work.table_field SET position=86 WHERE data='obscontexte' AND format='table_observation';
UPDATE metadata_work.table_field SET position=87 WHERE data='identifiantregroupementpermanent' AND format='table_observation';
UPDATE metadata_work.table_field SET position=88 WHERE data='methoderegroupement' AND format='table_observation';
UPDATE metadata_work.table_field SET position=89 WHERE data='typeregroupement' AND format='table_observation';
UPDATE metadata_work.table_field SET position=90 WHERE data='altitudemoyenne' AND format='table_observation';
UPDATE metadata_work.table_field SET position=91 WHERE data='profondeurmoyenne' AND format='table_observation';
UPDATE metadata_work.table_field SET position=92 WHERE data='geometrie' AND format='table_observation';
UPDATE metadata_work.table_field SET position=93 WHERE data='natureobjetgeo' AND format='table_observation';
UPDATE metadata_work.table_field SET position=94 WHERE data='precisiongeometrie' AND format='table_observation';
UPDATE metadata_work.table_field SET position=95 WHERE data='sensimanuelle' AND format='table_observation';
UPDATE metadata_work.table_field SET position=96 WHERE data='sensialerte' AND format='table_observation';
UPDATE metadata_work.table_field SET position=97 WHERE data='codemaillecalcule' AND format='table_observation';
UPDATE metadata_work.table_field SET position=98 WHERE data='codecommunecalcule' AND format='table_observation';
UPDATE metadata_work.table_field SET position=99 WHERE data='nomcommunecalcule' AND format='table_observation';
UPDATE metadata_work.table_field SET position=100 WHERE data='codedepartementcalcule' AND format='table_observation';
UPDATE metadata_work.table_field SET position=101 WHERE data='heuredatedebut' AND format='table_observation';
UPDATE metadata_work.table_field SET position=102 WHERE data='heuredatefin' AND format='table_observation';
UPDATE metadata_work.table_field SET position=103 WHERE data='nomvalide' AND format='table_observation';


UPDATE metadata.form_field SET "position"=1 WHERE data='cdnom' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=2 WHERE data='altitudemin' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=3 WHERE data='altitudemoyenne' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=4 WHERE data='anneerefcommune' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=5 WHERE data='anneerefdepartement' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=6 WHERE data='cdnom' AND format='form_observation';
UPDATE metadata.form_field SET "position"=7 WHERE data='cdref' AND format='form_observation';
UPDATE metadata.form_field SET "position"=8 WHERE data='codecommune' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=9 WHERE data='codedepartement' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=10 WHERE data='codeen' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=11 WHERE data='codehabitat' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=12 WHERE data='codehabref' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=13 WHERE data='codeidcnpdispositif' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=14 WHERE data='codemaille' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=15 WHERE data='codeme' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=16 WHERE data='commentaire' AND format='form_observation';
UPDATE metadata.form_field SET "position"=17 WHERE data='jourdatedebut' AND format='form_observation';
UPDATE metadata.form_field SET "position"=18 WHERE data='datedetermination' AND format='form_observation';
UPDATE metadata.form_field SET "position"=19 WHERE data='jourdatefin' AND format='form_observation';
UPDATE metadata.form_field SET "position"=20 WHERE data='dateme' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=21 WHERE data='deedatedernieremodification' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=22 WHERE data='deefloutage' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=23 WHERE data='denombrementmax' AND format='form_observation';
UPDATE metadata.form_field SET "position"=24 WHERE data='denombrementmin' AND format='form_observation';
UPDATE metadata.form_field SET "position"=25 WHERE data='determinateuridentite' AND format='form_observation';
UPDATE metadata.form_field SET "position"=26 WHERE data='determinateurmail' AND format='form_observation';
UPDATE metadata.form_field SET "position"=27 WHERE data='determinateurnomorganisme' AND format='form_observation';
UPDATE metadata.form_field SET "position"=28 WHERE data='diffusionniveauprecision' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=29 WHERE data='dspublique' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=30 WHERE data='geometrie' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=31 WHERE data='identifiantorigine' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=32 WHERE data='identifiantpermanent' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=33 WHERE data='identifiantregroupementpermanent' AND format='form_regroupements';
UPDATE metadata.form_field SET "position"=34 WHERE data='jddcode' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=35 WHERE data='jddid' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=36 WHERE data='jddmetadonneedeeid' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=37 WHERE data='jddsourceid' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=38 WHERE data='methoderegroupement' AND format='form_regroupements';
UPDATE metadata.form_field SET "position"=39 WHERE data='natureobjetgeo' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=40 WHERE data='nomcite' AND format='form_observation';
UPDATE metadata.form_field SET "position"=41 WHERE data='nomcommune' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=42 WHERE data='nomrefmaille' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=43 WHERE data='objetdenombrement' AND format='form_observation';
UPDATE metadata.form_field SET "position"=44 WHERE data='obscontexte' AND format='form_observation';
UPDATE metadata.form_field SET "position"=45 WHERE data='obsdescription' AND format='form_observation';
UPDATE metadata.form_field SET "position"=46 WHERE data='observateuridentite' AND format='form_observation';
UPDATE metadata.form_field SET "position"=47 WHERE data='observateurmail' AND format='form_observation';
UPDATE metadata.form_field SET "position"=48 WHERE data='observateurnomorganisme' AND format='form_observation';
UPDATE metadata.form_field SET "position"=49 WHERE data='obsmethode' AND format='form_observation';
UPDATE metadata.form_field SET "position"=50 WHERE data='occetatbiologique' AND format='form_observation';
UPDATE metadata.form_field SET "position"=51 WHERE data='occmethodedetermination' AND format='form_observation';
UPDATE metadata.form_field SET "position"=52 WHERE data='occnaturalite' AND format='form_observation';
UPDATE metadata.form_field SET "position"=53 WHERE data='occsexe' AND format='form_observation';
UPDATE metadata.form_field SET "position"=54 WHERE data='occstadedevie' AND format='form_observation';
UPDATE metadata.form_field SET "position"=55 WHERE data='occstatutbiogeographique' AND format='form_observation';
UPDATE metadata.form_field SET "position"=56 WHERE data='occstatutbiologique' AND format='form_observation';
UPDATE metadata.form_field SET "position"=57 WHERE data='OGAM_ID_table_observation' AND format='form_autres';
UPDATE metadata.form_field SET "position"=58 WHERE data='organismegestionnairedonnee' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=59 WHERE data='organismestandard' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=60 WHERE data='orgtransformation' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=61 WHERE data='precisiongeometrie' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=62 WHERE data='preuveexistante' AND format='form_observation';
UPDATE metadata.form_field SET "position"=63 WHERE data='preuvenonnumerique' AND format='form_observation';
UPDATE metadata.form_field SET "position"=64 WHERE data='preuvenumerique' AND format='form_observation';
UPDATE metadata.form_field SET "position"=65 WHERE data='profondeurmax' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=66 WHERE data='profondeurmin' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=67 WHERE data='profondeurmoyenne' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=68 WHERE data='PROVIDER_ID' AND format='form_autres';
UPDATE metadata.form_field SET "position"=69 WHERE data='referencebiblio' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=70 WHERE data='refhabitat' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=71 WHERE data='sensible' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=72 WHERE data='sensidateattribution' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=73 WHERE data='sensiniveau' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=74 WHERE data='sensireferentiel' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=75 WHERE data='sensiversionreferentiel' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=76 WHERE data='statutobservation' AND format='form_observation';
UPDATE metadata.form_field SET "position"=77 WHERE data='statutsource' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=78 WHERE data='SUBMISSION_ID' AND format='form_autres';
UPDATE metadata.form_field SET "position"=79 WHERE data='typedenombrement' AND format='form_observation';
UPDATE metadata.form_field SET "position"=80 WHERE data='typeen' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=81 WHERE data='typeinfogeocommune' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=82 WHERE data='typeinfogeodepartement' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=83 WHERE data='typeinfogeoen' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=84 WHERE data='typeinfogeomaille' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=85 WHERE data='typeinfogeome' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=86 WHERE data='typeregroupement' AND format='form_regroupements';
UPDATE metadata.form_field SET "position"=87 WHERE data='validateuridentite' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=88 WHERE data='validateurmail' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=89 WHERE data='validateurnomorganisme' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=90 WHERE data='versionen' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=91 WHERE data='versionme' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=92 WHERE data='versionrefhabitat' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=93 WHERE data='versionrefmaille' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=94 WHERE data='versiontaxref' AND format='form_observation';
UPDATE metadata.form_field SET "position"=95 WHERE data='sensimanuelle' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=96 WHERE data='sensialerte' AND format='form_standardisation';
UPDATE metadata.form_field SET "position"=97 WHERE data='codemaillecalcule' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=98 WHERE data='codecommunecalcule' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=99 WHERE data='nomcommunecalcule' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=100 WHERE data='codedepartementcalcule' AND format='form_localisation';
UPDATE metadata.form_field SET "position"=101 WHERE data='heuredatedebut' AND format='form_observation';
UPDATE metadata.form_field SET "position"=102 WHERE data='heuredatefin' AND format='form_observation';
UPDATE metadata.form_field SET "position"=103 WHERE data='nomvalide' AND format='form_observation';

UPDATE metadata_work.form_field SET "position"=1 WHERE data='cdnom' AND format='form_localisation';                                             
UPDATE metadata_work.form_field SET "position"=2 WHERE data='altitudemin' AND format='form_localisation';                                       
UPDATE metadata_work.form_field SET "position"=3 WHERE data='altitudemoyenne' AND format='form_localisation';                                   
UPDATE metadata_work.form_field SET "position"=4 WHERE data='anneerefcommune' AND format='form_localisation';                                   
UPDATE metadata_work.form_field SET "position"=5 WHERE data='anneerefdepartement' AND format='form_localisation';                               
UPDATE metadata_work.form_field SET "position"=6 WHERE data='cdnom' AND format='form_observation';                                              
UPDATE metadata_work.form_field SET "position"=7 WHERE data='cdref' AND format='form_observation';                                              
UPDATE metadata_work.form_field SET "position"=8 WHERE data='codecommune' AND format='form_localisation';                                       
UPDATE metadata_work.form_field SET "position"=9 WHERE data='codedepartement' AND format='form_localisation';                                   
UPDATE metadata_work.form_field SET "position"=10 WHERE data='codeen' AND format='form_localisation';                                           
UPDATE metadata_work.form_field SET "position"=11 WHERE data='codehabitat' AND format='form_localisation';                                      
UPDATE metadata_work.form_field SET "position"=12 WHERE data='codehabref' AND format='form_localisation';                                       
UPDATE metadata_work.form_field SET "position"=13 WHERE data='codeidcnpdispositif' AND format='form_standardisation';                           
UPDATE metadata_work.form_field SET "position"=14 WHERE data='codemaille' AND format='form_localisation';                                       
UPDATE metadata_work.form_field SET "position"=15 WHERE data='codeme' AND format='form_localisation';                                           
UPDATE metadata_work.form_field SET "position"=16 WHERE data='commentaire' AND format='form_observation';                                       
UPDATE metadata_work.form_field SET "position"=17 WHERE data='jourdatedebut' AND format='form_observation';                                     
UPDATE metadata_work.form_field SET "position"=18 WHERE data='datedetermination' AND format='form_observation';                                 
UPDATE metadata_work.form_field SET "position"=19 WHERE data='jourdatefin' AND format='form_observation';                                       
UPDATE metadata_work.form_field SET "position"=20 WHERE data='dateme' AND format='form_localisation';                                           
UPDATE metadata_work.form_field SET "position"=21 WHERE data='deedatedernieremodification' AND format='form_standardisation';                   
UPDATE metadata_work.form_field SET "position"=22 WHERE data='deefloutage' AND format='form_standardisation';                                   
UPDATE metadata_work.form_field SET "position"=23 WHERE data='denombrementmax' AND format='form_observation';                                   
UPDATE metadata_work.form_field SET "position"=24 WHERE data='denombrementmin' AND format='form_observation';                                   
UPDATE metadata_work.form_field SET "position"=25 WHERE data='determinateuridentite' AND format='form_observation';                             
UPDATE metadata_work.form_field SET "position"=26 WHERE data='determinateurmail' AND format='form_observation';                                 
UPDATE metadata_work.form_field SET "position"=27 WHERE data='determinateurnomorganisme' AND format='form_observation';                         
UPDATE metadata_work.form_field SET "position"=28 WHERE data='diffusionniveauprecision' AND format='form_standardisation';                      
UPDATE metadata_work.form_field SET "position"=29 WHERE data='dspublique' AND format='form_standardisation';                                    
UPDATE metadata_work.form_field SET "position"=30 WHERE data='geometrie' AND format='form_localisation';                                        
UPDATE metadata_work.form_field SET "position"=31 WHERE data='identifiantorigine' AND format='form_standardisation';                            
UPDATE metadata_work.form_field SET "position"=32 WHERE data='identifiantpermanent' AND format='form_standardisation';                          
UPDATE metadata_work.form_field SET "position"=33 WHERE data='identifiantregroupementpermanent' AND format='form_regroupements';                
UPDATE metadata_work.form_field SET "position"=34 WHERE data='jddcode' AND format='form_standardisation';                                       
UPDATE metadata_work.form_field SET "position"=35 WHERE data='jddid' AND format='form_standardisation';                                         
UPDATE metadata_work.form_field SET "position"=36 WHERE data='jddmetadonneedeeid' AND format='form_standardisation';                            
UPDATE metadata_work.form_field SET "position"=37 WHERE data='jddsourceid' AND format='form_standardisation';                                   
UPDATE metadata_work.form_field SET "position"=38 WHERE data='methoderegroupement' AND format='form_regroupements';                             
UPDATE metadata_work.form_field SET "position"=39 WHERE data='natureobjetgeo' AND format='form_localisation';                                   
UPDATE metadata_work.form_field SET "position"=40 WHERE data='nomcite' AND format='form_observation';                                           
UPDATE metadata_work.form_field SET "position"=41 WHERE data='nomcommune' AND format='form_localisation';                                       
UPDATE metadata_work.form_field SET "position"=42 WHERE data='nomrefmaille' AND format='form_localisation';                                     
UPDATE metadata_work.form_field SET "position"=43 WHERE data='objetdenombrement' AND format='form_observation';                                 
UPDATE metadata_work.form_field SET "position"=44 WHERE data='obscontexte' AND format='form_observation';                                       
UPDATE metadata_work.form_field SET "position"=45 WHERE data='obsdescription' AND format='form_observation';                                    
UPDATE metadata_work.form_field SET "position"=46 WHERE data='observateuridentite' AND format='form_observation';                               
UPDATE metadata_work.form_field SET "position"=47 WHERE data='observateurmail' AND format='form_observation';                                   
UPDATE metadata_work.form_field SET "position"=48 WHERE data='observateurnomorganisme' AND format='form_observation';                           
UPDATE metadata_work.form_field SET "position"=49 WHERE data='obsmethode' AND format='form_observation';                                        
UPDATE metadata_work.form_field SET "position"=50 WHERE data='occetatbiologique' AND format='form_observation';                                 
UPDATE metadata_work.form_field SET "position"=51 WHERE data='occmethodedetermination' AND format='form_observation';                           
UPDATE metadata_work.form_field SET "position"=52 WHERE data='occnaturalite' AND format='form_observation';                                     
UPDATE metadata_work.form_field SET "position"=53 WHERE data='occsexe' AND format='form_observation';                                           
UPDATE metadata_work.form_field SET "position"=54 WHERE data='occstadedevie' AND format='form_observation';                                     
UPDATE metadata_work.form_field SET "position"=55 WHERE data='occstatutbiogeographique' AND format='form_observation';                          
UPDATE metadata_work.form_field SET "position"=56 WHERE data='occstatutbiologique' AND format='form_observation';                               
UPDATE metadata_work.form_field SET "position"=57 WHERE data='OGAM_ID_table_observation' AND format='form_autres';                              
UPDATE metadata_work.form_field SET "position"=58 WHERE data='organismegestionnairedonnee' AND format='form_standardisation';                   
UPDATE metadata_work.form_field SET "position"=59 WHERE data='organismestandard' AND format='form_standardisation';                             
UPDATE metadata_work.form_field SET "position"=60 WHERE data='orgtransformation' AND format='form_standardisation';                             
UPDATE metadata_work.form_field SET "position"=61 WHERE data='precisiongeometrie' AND format='form_localisation';                               
UPDATE metadata_work.form_field SET "position"=62 WHERE data='preuveexistante' AND format='form_observation';                                   
UPDATE metadata_work.form_field SET "position"=63 WHERE data='preuvenonnumerique' AND format='form_observation';                                
UPDATE metadata_work.form_field SET "position"=64 WHERE data='preuvenumerique' AND format='form_observation';                                   
UPDATE metadata_work.form_field SET "position"=65 WHERE data='profondeurmax' AND format='form_localisation';                                    
UPDATE metadata_work.form_field SET "position"=66 WHERE data='profondeurmin' AND format='form_localisation';                                    
UPDATE metadata_work.form_field SET "position"=67 WHERE data='profondeurmoyenne' AND format='form_localisation';                                
UPDATE metadata_work.form_field SET "position"=68 WHERE data='PROVIDER_ID' AND format='form_autres';                                            
UPDATE metadata_work.form_field SET "position"=69 WHERE data='referencebiblio' AND format='form_standardisation';                               
UPDATE metadata_work.form_field SET "position"=70 WHERE data='refhabitat' AND format='form_localisation';                                       
UPDATE metadata_work.form_field SET "position"=71 WHERE data='sensible' AND format='form_standardisation';                                      
UPDATE metadata_work.form_field SET "position"=72 WHERE data='sensidateattribution' AND format='form_standardisation';                          
UPDATE metadata_work.form_field SET "position"=73 WHERE data='sensiniveau' AND format='form_standardisation';                                   
UPDATE metadata_work.form_field SET "position"=74 WHERE data='sensireferentiel' AND format='form_standardisation';                              
UPDATE metadata_work.form_field SET "position"=75 WHERE data='sensiversionreferentiel' AND format='form_standardisation';                       
UPDATE metadata_work.form_field SET "position"=76 WHERE data='statutobservation' AND format='form_observation';                                 
UPDATE metadata_work.form_field SET "position"=77 WHERE data='statutsource' AND format='form_standardisation';                                  
UPDATE metadata_work.form_field SET "position"=78 WHERE data='SUBMISSION_ID' AND format='form_autres';                                          
UPDATE metadata_work.form_field SET "position"=79 WHERE data='typedenombrement' AND format='form_observation';                                  
UPDATE metadata_work.form_field SET "position"=80 WHERE data='typeen' AND format='form_localisation';                                           
UPDATE metadata_work.form_field SET "position"=81 WHERE data='typeinfogeocommune' AND format='form_localisation';                               
UPDATE metadata_work.form_field SET "position"=82 WHERE data='typeinfogeodepartement' AND format='form_localisation';                           
UPDATE metadata_work.form_field SET "position"=83 WHERE data='typeinfogeoen' AND format='form_localisation';                                    
UPDATE metadata_work.form_field SET "position"=84 WHERE data='typeinfogeomaille' AND format='form_localisation';                                
UPDATE metadata_work.form_field SET "position"=85 WHERE data='typeinfogeome' AND format='form_localisation';                                    
UPDATE metadata_work.form_field SET "position"=86 WHERE data='typeregroupement' AND format='form_regroupements';                                
UPDATE metadata_work.form_field SET "position"=87 WHERE data='validateuridentite' AND format='form_standardisation';                            
UPDATE metadata_work.form_field SET "position"=88 WHERE data='validateurmail' AND format='form_standardisation';                                
UPDATE metadata_work.form_field SET "position"=89 WHERE data='validateurnomorganisme' AND format='form_standardisation';                        
UPDATE metadata_work.form_field SET "position"=90 WHERE data='versionen' AND format='form_localisation';                                        
UPDATE metadata_work.form_field SET "position"=91 WHERE data='versionme' AND format='form_localisation';                                        
UPDATE metadata_work.form_field SET "position"=92 WHERE data='versionrefhabitat' AND format='form_localisation';                                
UPDATE metadata_work.form_field SET "position"=93 WHERE data='versionrefmaille' AND format='form_localisation';                                 
UPDATE metadata_work.form_field SET "position"=94 WHERE data='versiontaxref' AND format='form_observation';                                     
UPDATE metadata_work.form_field SET "position"=95 WHERE data='sensimanuelle' AND format='form_standardisation';                                 
UPDATE metadata_work.form_field SET "position"=96 WHERE data='sensialerte' AND format='form_standardisation';                                   
UPDATE metadata_work.form_field SET "position"=97 WHERE data='codemaillecalcule' AND format='form_localisation';                                
UPDATE metadata_work.form_field SET "position"=98 WHERE data='codecommunecalcule' AND format='form_localisation';                               
UPDATE metadata_work.form_field SET "position"=99 WHERE data='nomcommunecalcule' AND format='form_localisation';                                
UPDATE metadata_work.form_field SET "position"=100 WHERE data='codedepartementcalcule' AND format='form_localisation';                          
UPDATE metadata_work.form_field SET "position"=101 WHERE data='heuredatedebut' AND format='form_observation';                                   
UPDATE metadata_work.form_field SET "position"=102 WHERE data='heuredatefin' AND format='form_observation';                                     
UPDATE metadata_work.form_field SET "position"=103 WHERE data='nomvalide' AND format='form_observation';                                        
                                                                                                                                        