<?php

namespace Ign\Bundle\GincoBundle\Repository\RawData;

use Doctrine\ORM\EntityRepository;

/**
 * ErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckErrorRepository extends EntityRepository
{
    public function getErrorCounts(\Ign\Bundle\GincoBundle\Entity\RawData\Submission $submission){
        
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT c.*, count(*) as count
                FROM raw_data.check_error ce
                INNER JOIN metadata.checks c USING(check_id)
                WHERE ce.submission_id = :submission_id
                GROUP BY c.check_id
                ORDER BY c.check_id ASC';

        $stmt = $conn->prepare($sql);
        $stmt->execute(array($submission->getId()));

        return $stmt->fetchAll();
    }
}
