<?php

namespace Ign\Bundle\GincoBundle\Repository\RawData;

use Doctrine\ORM\EntityRepository;

use Ign\Bundle\GincoBundle\Entity\RawData\Submission;

/**
 * ErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorRepository extends EntityRepository
{

}
