<?php
namespace Ign\Bundle\GincoBundle\Repository\RawData;

use Doctrine\Common\Collections\Collection;

/**
 * SubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmissionRepository extends \Doctrine\ORM\EntityRepository {

	/**
	 * Get some information about the active submissions.
	 *
	 * @param String $providerId
	 *        	provider to get the submissions from (null for all providers)
	 * @return Array[Submission]
	 */
	public function getActiveSubmissions($providerId = null) {
		$dql = "SELECT s " . "FROM IgnGincoBundle:RawData\Submission s " . "WHERE";

		$dql .= " (s.step NOT IN ('CANCEL', 'INIT') OR (s.step IN ('CANCEL') AND s.status IN ('RUNNING'))) ";

		if ($providerId !== null) {
			$dql .= " AND s.provider = :provider ";
		}

		$dql .= "ORDER BY s.id DESC";

		$query = $this->getEntityManager()->createQuery($dql);

		if ($providerId !== null) {
			$query->setParameter('provider', $providerId);
		}

		return $query->getResult();
	}
}
